/**
 * Writes src/data/products.ts from D1.
 *
 * The database is the source of truth for the catalogue; this file is the
 * build-time snapshot that lets the storefront paint without waiting for
 * /api/products. It keeps the path and the exports the hand-written file had,
 * so none of its importers know the difference — which is the whole reason
 * this is generation rather than a reactive rewrite of every consumer.
 *
 *   node scripts/build-catalog.mjs [database]        # default: production
 *   node scripts/build-catalog.mjs nexus-orders-staging
 *
 * The database name is an argument rather than only an env var because
 * `CATALOG_DB=x node ...` inside an npm script does not run on Windows, where
 * npm hands the line to cmd.exe.
 *
 * QUERY and toProduct are exported, and everything that touches D1 sits behind
 * the run-as-a-script guard at the foot of the file, so catalogue.spec.ts can
 * exercise both against an in-memory database without wrangler or a network.
 */
import { pathToFileURL } from 'node:url'

const OUT = 'src/data/products.ts'
const FLAGSHIP = 'DJI-MV4-115'

/**
 * Byte-for-byte the ORDER BY in worker/src/catalogue.ts's publishedProducts,
 * and it has to stay that way: this query writes the file the shop page
 * renders and that one answers /api/products about the same rows. They agree
 * today only because every seeded row has a distinct display_order, so the
 * tiebreaker never runs — the first product created without one takes the
 * DEFAULT 0, ties with iphone-18-pro, and the two orderings part company.
 *
 * display_order leads for a separate reason: 0008 inserted every row in one
 * batch, so they all share a created_at, and ordering by that alone returns
 * the catalogue alphabetically by id — phones interleaved with laptops. See
 * migrations/0010-display-order.sql.
 */
export const QUERY =
  `SELECT p.* FROM products p JOIN merchants m ON m.id = p.merchant_id
      WHERE p.status = 'published' AND m.status = 'active'
      ORDER BY p.display_order, p.created_at DESC, p.id`

/** One D1 row as the storefront's Product. */
export const toProduct = (r) => ({
  id: r.id,
  sku: r.sku,
  brand: r.brand,
  title: r.title,
  category: r.category,
  priceMinor: r.price_minor,
  currency: r.currency,
  // Not a column: derived, the same way the hand-written file derived it.
  inStock: r.stock_count > 0,
  stockCount: r.stock_count,
  // undefined rather than null, so JSON.stringify drops the key and the
  // optional property stays absent as it was when hand-written.
  badge: r.badge ?? undefined,
  rating: r.rating,
  reviewCount: r.review_count,
  specsSummary: JSON.parse(r.specs_summary),
  specs: JSON.parse(r.specs),
  media: JSON.parse(r.media),
  colorways: JSON.parse(r.colorways),
})

function render(products) {
  return (
    `// GENERATED by scripts/build-catalog.mjs from D1. Do not edit by hand.\n` +
    `// The database is the source of truth; this file is the build-time snapshot\n` +
    `// that lets the storefront render its first paint without the API.\n` +
    `//\n` +
    `// Row order is the catalogue's display order and is rendered as-is by the\n` +
    `// shop page, so it is behaviour. It comes from products.display_order.\n` +
    `import type { Product } from '@/types'\n\n` +
    `export const products: Product[] = ${JSON.stringify(products, null, 2)}\n\n` +
    `/** The hero's featured drop. */\n` +
    `export const featuredDrop: Product = products.find((p) => p.sku === '${FLAGSHIP}')!\n`
  )
}

// Run as a script, not imported. `import.meta.main` is Node 24; this is the
// same test on 22.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { execFileSync } = await import('node:child_process')
  const { writeFileSync } = await import('node:fs')
  const { createRequire } = await import('node:module')
  const path = (await import('node:path')).default

  const DB = process.argv[2] ?? process.env.CATALOG_DB ?? 'nexus-orders'
  const REMOTE = process.env.CATALOG_LOCAL ? [] : ['--remote']

  // wrangler's own entry point, run with this node. `npx wrangler` cannot be
  // spawned without a shell on Windows — it resolves to a .cmd — and putting a
  // SQL string through a shell is a quoting bug waiting to happen.
  // bin/ is not in wrangler's `exports` map, so it is reached from the package
  // root rather than resolved directly. The main entry is wrangler-dist/cli.js.
  const wrangler = path.join(
    createRequire(import.meta.url).resolve('wrangler', { paths: [path.join(process.cwd(), 'worker')] }),
    '../../bin/wrangler.js',
  )

  const out = execFileSync(
    process.execPath,
    [wrangler, 'd1', 'execute', DB, ...REMOTE, '--json', '--command', QUERY],
    { cwd: 'worker', encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  )

  // `--json` prints a one-element array: [{ results, success, meta }].
  const { results } = JSON.parse(out)[0]

  if (!results?.length) throw new Error(`${DB} returned no published products`)

  const products = results.map(toProduct)

  // The hero renders this one unconditionally. A missing flagship must stop the
  // build here rather than reach the page as `undefined!`.
  if (!products.some((p) => p.sku === FLAGSHIP)) {
    throw new Error(`the flagship SKU ${FLAGSHIP} is not published in ${DB}`)
  }

  writeFileSync(OUT, render(products))

  console.log(`wrote ${products.length} products from ${DB}`)
}
