// GENERATED by scripts/build-catalog.mjs from D1. Do not edit by hand.
// The database is the source of truth; this file is the build-time snapshot
// that lets the storefront render its first paint without the API.
//
// Row order is the catalogue's display order and is rendered as-is by the
// shop page, so it is behaviour. It comes from products.display_order.
import type { Product } from '@/types'

export const products: Product[] = [
  {
    "id": "iphone-18-pro",
    "sku": "APL-IP18P-256",
    "brand": "APPLE",
    "title": "iPhone 18 Pro",
    "category": "phones",
    "priceMinor": 119900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 48,
    "badge": "NEW_DROP",
    "rating": 4.8,
    "reviewCount": 2317,
    "specsSummary": [
      "A20 Pro, 2nm",
      "48MP variable aperture",
      "36-hour video playback"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Apple A20 Pro, 2nm, 6-core CPU / 7-core GPU"
      },
      {
        "label": "Neural Engine",
        "value": "Dual 16-core"
      },
      {
        "label": "Display",
        "value": "6.3in Super Retina XDR, ProMotion 120Hz"
      },
      {
        "label": "Main camera",
        "value": "48MP Fusion with variable aperture"
      },
      {
        "label": "Aperture",
        "value": "Six laser-cut blades, f/1.48 to f/4"
      },
      {
        "label": "Battery",
        "value": "Up to 36 hours video playback"
      },
      {
        "label": "Charging",
        "value": "50% in 15 min wired, 30 min wireless"
      },
      {
        "label": "Storage",
        "value": "256GB / 512GB / 1TB / 2TB"
      },
      {
        "label": "SIM",
        "value": "eSIM only"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/iphone-18-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/iphone-18-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/iphone-18-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/iphone-18-pro-1.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-2.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-3.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Burgundy",
        "hex": "#6E2639"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Glacier",
        "hex": "#BFD4E4"
      }
    ]
  },
  {
    "id": "iphone-18-pro-max",
    "sku": "APL-IP18PM-256",
    "brand": "APPLE",
    "title": "iPhone 18 Pro Max",
    "category": "phones",
    "priceMinor": 129900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "badge": "NEW_DROP",
    "rating": 4.9,
    "reviewCount": 1508,
    "specsSummary": [
      "A20 Pro, 2nm",
      "Longest battery in an iPhone",
      "45-hour video playback"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Apple A20 Pro, 2nm, 6-core CPU / 7-core GPU"
      },
      {
        "label": "Neural Engine",
        "value": "Dual 16-core"
      },
      {
        "label": "Display",
        "value": "6.9in Super Retina XDR, ProMotion 120Hz"
      },
      {
        "label": "Main camera",
        "value": "48MP Fusion with variable aperture"
      },
      {
        "label": "Aperture",
        "value": "Six laser-cut blades, f/1.48 to f/4"
      },
      {
        "label": "Battery",
        "value": "Up to 45 hours video playback"
      },
      {
        "label": "Charging",
        "value": "50% in 15 min wired, 30 min wireless"
      },
      {
        "label": "Storage",
        "value": "256GB / 512GB / 1TB / 2TB"
      },
      {
        "label": "SIM",
        "value": "eSIM only"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/iphone-18-pro-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/iphone-18-pro-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/iphone-18-pro-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/iphone-18-pro-max-1.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-2.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-3.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Burgundy",
        "hex": "#6E2639"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Glacier",
        "hex": "#BFD4E4"
      }
    ]
  },
  {
    "id": "galaxy-s26-ultra",
    "sku": "SAM-S26U-256",
    "brand": "SAMSUNG",
    "title": "Galaxy S26 Ultra",
    "category": "phones",
    "priceMinor": 129999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 42,
    "rating": 4.7,
    "reviewCount": 3106,
    "specsSummary": [
      "200MP f/1.4 main camera",
      "Snapdragon 8 Elite Gen 5",
      "60W wired charging"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Snapdragon 8 Elite Gen 5 for Galaxy"
      },
      {
        "label": "Display",
        "value": "6.9in anti-reflective, pixel-level Privacy Display"
      },
      {
        "label": "Frame",
        "value": "Armor Aluminium, rounded corners"
      },
      {
        "label": "Main camera",
        "value": "200MP, f/1.4"
      },
      {
        "label": "Battery",
        "value": "5,000mAh"
      },
      {
        "label": "Charging",
        "value": "60W wired, 15W wireless"
      },
      {
        "label": "Storage",
        "value": "256GB / 512GB / 1TB"
      },
      {
        "label": "S Pen",
        "value": "Included, in-body silo"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-s26-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-s26-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-s26-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-s26-ultra-1.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-2.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-3.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Cobalt Violet",
        "hex": "#4B4A8F"
      },
      {
        "name": "Sky Blue",
        "hex": "#9FC4E2"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "pixel-11-pro",
    "sku": "GGL-P11P-256",
    "brand": "GOOGLE",
    "title": "Pixel 11 Pro",
    "category": "phones",
    "priceMinor": 109900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 37,
    "badge": "NEW_DROP",
    "rating": 4.6,
    "reviewCount": 1274,
    "specsSummary": [
      "Google G6, 2nm",
      "Triple 50MP-class cameras",
      "Android 17"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Google G6, 2nm"
      },
      {
        "label": "Memory",
        "value": "12GB LPDDR5X"
      },
      {
        "label": "Display",
        "value": "6.3in LTPO OLED, 120Hz"
      },
      {
        "label": "Rear cameras",
        "value": "50MP main + 48MP ultrawide + 48MP telephoto"
      },
      {
        "label": "Front camera",
        "value": "42MP"
      },
      {
        "label": "Battery",
        "value": "4,850mAh"
      },
      {
        "label": "Storage",
        "value": "256GB (128GB discontinued)"
      },
      {
        "label": "Rating",
        "value": "IP68"
      },
      {
        "label": "Software",
        "value": "Android 17"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/pixel-11-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/pixel-11-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/pixel-11-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/pixel-11-pro-1.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-2.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-3.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Porcelain",
        "hex": "#E6E0D6"
      },
      {
        "name": "Jade",
        "hex": "#3E6B5A"
      }
    ]
  },
  {
    "id": "oneplus-15",
    "sku": "OPO-15-256",
    "brand": "ONEPLUS",
    "title": "OnePlus 15",
    "category": "phones",
    "priceMinor": 89999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 55,
    "rating": 4.5,
    "reviewCount": 2044,
    "specsSummary": [
      "7,300mAh battery",
      "165Hz LTPO AMOLED",
      "120W wired charging"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Snapdragon 8 Elite Gen 5"
      },
      {
        "label": "Memory",
        "value": "12GB LPDDR5X"
      },
      {
        "label": "Display",
        "value": "6.78in LTPO AMOLED, 165Hz"
      },
      {
        "label": "Rear cameras",
        "value": "50MP + 50MP + 50MP triple"
      },
      {
        "label": "Front camera",
        "value": "32MP"
      },
      {
        "label": "Battery",
        "value": "7,300mAh"
      },
      {
        "label": "Charging",
        "value": "120W wired"
      },
      {
        "label": "Rating",
        "value": "IP66 / IP68 / IP69K"
      },
      {
        "label": "Software",
        "value": "Android 16"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/oneplus-15-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/oneplus-15-2.webp",
      "thumb": "https://media.nexusohm.com/products/oneplus-15-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/oneplus-15-1.webp",
        "https://media.nexusohm.com/products/oneplus-15-2.webp",
        "https://media.nexusohm.com/products/oneplus-15-3.webp",
        "https://media.nexusohm.com/products/oneplus-15-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Cobalt Violet",
        "hex": "#4B4A8F"
      },
      {
        "name": "Sand Storm",
        "hex": "#C2A878"
      }
    ]
  },
  {
    "id": "xiaomi-17-ultra",
    "sku": "XMI-17U-512",
    "brand": "XIAOMI",
    "title": "Xiaomi 17 Ultra",
    "category": "phones",
    "priceMinor": 129900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 22,
    "rating": 4.6,
    "reviewCount": 734,
    "specsSummary": [
      "1-inch Leica main sensor",
      "200MP periscope telephoto",
      "90W wired charging"
    ],
    "specs": [
      {
        "label": "Camera system",
        "value": "Leica, triple rear"
      },
      {
        "label": "Main camera",
        "value": "50MP 1in Light Fusion 1050L"
      },
      {
        "label": "Telephoto",
        "value": "200MP Samsung HPE 1/1.4in periscope, continuous zoom"
      },
      {
        "label": "Ultrawide",
        "value": "50MP with autofocus"
      },
      {
        "label": "Display",
        "value": "6.9in M10 AMOLED LTPO, 2608x1200, 120Hz"
      },
      {
        "label": "Brightness",
        "value": "Up to 3,500 nits peak"
      },
      {
        "label": "Battery",
        "value": "6,000mAh"
      },
      {
        "label": "Charging",
        "value": "90W wired, 50W wireless"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/xiaomi-17-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/xiaomi-17-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/xiaomi-17-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/xiaomi-17-ultra-1.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-2.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-3.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Sand Storm",
        "hex": "#C2A878"
      }
    ]
  },
  {
    "id": "xps-16",
    "sku": "DEL-XPS16-26",
    "brand": "DELL",
    "title": "XPS 16 (2026)",
    "category": "computing",
    "priceMinor": 174900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 24,
    "badge": "NEW_DROP",
    "rating": 4.5,
    "reviewCount": 612,
    "specsSummary": [
      "16in tandem OLED",
      "Intel Panther Lake",
      "CNC aluminium chassis"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Intel Core Ultra, Panther Lake"
      },
      {
        "label": "Display",
        "value": "16in InfinityEdge tandem OLED, 2880x1800, touch"
      },
      {
        "label": "Chassis",
        "value": "CNC-machined aluminium, rounded corners"
      },
      {
        "label": "Memory",
        "value": "16GB LPDDR5X, up to 64GB"
      },
      {
        "label": "Storage",
        "value": "512GB SSD, up to 4TB"
      },
      {
        "label": "Keyboard",
        "value": "Physical function row, haptic touchpad"
      },
      {
        "label": "Ports",
        "value": "3x Thunderbolt 4 USB-C with DisplayPort 2.1 and power delivery, 3.5mm combo"
      },
      {
        "label": "Top configuration",
        "value": "Core Ultra X7 / 64GB / 4TB at $3,449"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/xps-16-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/xps-16-2.webp",
      "thumb": "https://media.nexusohm.com/products/xps-16-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/xps-16-1.webp",
        "https://media.nexusohm.com/products/xps-16-2.webp",
        "https://media.nexusohm.com/products/xps-16-3.webp",
        "https://media.nexusohm.com/products/xps-16-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Platinum",
        "hex": "#C9CBD0"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "thinkpad-x1-carbon",
    "sku": "LEN-X1C14-26",
    "brand": "LENOVO",
    "title": "ThinkPad X1 Carbon Gen 14",
    "category": "computing",
    "priceMinor": 199900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 18,
    "rating": 4.7,
    "reviewCount": 1103,
    "specsSummary": [
      "Intel Arc B390 graphics",
      "Serviceable chassis",
      "Windows 11 Pro"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Intel Core Ultra X7 358H, Panther Lake"
      },
      {
        "label": "Graphics",
        "value": "Intel Arc B390"
      },
      {
        "label": "Display",
        "value": "14in WUXGA 1920x1200 IPS, matte OLED optional"
      },
      {
        "label": "Memory",
        "value": "Up to 64GB"
      },
      {
        "label": "Storage",
        "value": "Up to 2TB SSD"
      },
      {
        "label": "Operating system",
        "value": "Windows 11 Pro"
      },
      {
        "label": "Ports",
        "value": "3x Thunderbolt 4 USB-C at 40Gbps with 65W power delivery, HDMI 2.1, USB-A, 3.5mm combo"
      },
      {
        "label": "Battery",
        "value": "Close to 24 hours in review testing"
      },
      {
        "label": "Weight",
        "value": "2.15 lb"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/thinkpad-x1-carbon-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/thinkpad-x1-carbon-2.webp",
      "thumb": "https://media.nexusohm.com/products/thinkpad-x1-carbon-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-1.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-2.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-3.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "zenbook-s14",
    "sku": "ASU-ZS14-26",
    "brand": "ASUS",
    "title": "Zenbook S14 (2026)",
    "category": "computing",
    "priceMinor": 189900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "badge": "NEW_DROP",
    "rating": 4.6,
    "reviewCount": 487,
    "specsSummary": [
      "50 TOPS NPU",
      "14in 3K OLED touch",
      "32GB / 1TB"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Intel Core Ultra 9 386H, 16-core, 2.1GHz"
      },
      {
        "label": "NPU",
        "value": "Up to 50 TOPS, Copilot+ certified"
      },
      {
        "label": "Graphics",
        "value": "Intel Arc integrated"
      },
      {
        "label": "Display",
        "value": "14in OLED 3K touchscreen"
      },
      {
        "label": "Memory",
        "value": "32GB LPDDR5X, soldered"
      },
      {
        "label": "Storage",
        "value": "1TB PCIe Gen 4 SSD"
      },
      {
        "label": "Finish",
        "value": "Scandinavian White, ceraluminium lid"
      },
      {
        "label": "Class",
        "value": "Copilot+ PC"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/zenbook-s14-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/zenbook-s14-2.webp",
      "thumb": "https://media.nexusohm.com/products/zenbook-s14-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/zenbook-s14-1.webp",
        "https://media.nexusohm.com/products/zenbook-s14-2.webp",
        "https://media.nexusohm.com/products/zenbook-s14-3.webp",
        "https://media.nexusohm.com/products/zenbook-s14-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Scandinavian White",
        "hex": "#E9E6DF"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "zenbook-duo",
    "sku": "ASU-ZDUO-26",
    "brand": "ASUS",
    "title": "Zenbook Duo (2026)",
    "category": "computing",
    "priceMinor": 249999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "badge": "LIMITED_EDITION",
    "rating": 4.4,
    "reviewCount": 203,
    "specsSummary": [
      "Two OLED screens",
      "Detachable keyboard",
      "Intel Core Ultra Series 3"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Intel Core Ultra Series 3, X9 388H on the top trim"
      },
      {
        "label": "Displays",
        "value": "Two full-size OLED panels"
      },
      {
        "label": "Graphics",
        "value": "Intel Arc integrated"
      },
      {
        "label": "NPU",
        "value": "Copilot+ class"
      },
      {
        "label": "Keyboard",
        "value": "Detachable Bluetooth, stows between the screens"
      },
      {
        "label": "Stand",
        "value": "Built-in kickstand for stacked or side-by-side use"
      },
      {
        "label": "Top configuration",
        "value": "Core Ultra X9 388H at $2,699.99"
      },
      {
        "label": "Announced",
        "value": "CES 2026"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/zenbook-duo-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/zenbook-duo-2.webp",
      "thumb": "https://media.nexusohm.com/products/zenbook-duo-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/zenbook-duo-1.webp",
        "https://media.nexusohm.com/products/zenbook-duo-2.webp",
        "https://media.nexusohm.com/products/zenbook-duo-3.webp",
        "https://media.nexusohm.com/products/zenbook-duo-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Inkwell Grey",
        "hex": "#40434A"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "airpods-max",
    "sku": "APL-APM2-101",
    "brand": "APPLE",
    "title": "AirPods Max (2nd gen)",
    "category": "audio",
    "priceMinor": 54900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 34,
    "badge": "NEW_DROP",
    "rating": 4.7,
    "reviewCount": 1842,
    "specsSummary": [
      "Adaptive noise cancellation",
      "Spatial audio",
      "20-hour battery"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "40mm dynamic, custom Apple"
      },
      {
        "label": "Noise control",
        "value": "Active ANC with Transparency"
      },
      {
        "label": "Battery",
        "value": "20 hours with ANC on"
      },
      {
        "label": "Chip",
        "value": "Apple H2, one per cup"
      },
      {
        "label": "Audio",
        "value": "Personalised Spatial Audio, head tracking"
      },
      {
        "label": "Connectivity",
        "value": "Bluetooth 5.3, USB-C"
      },
      {
        "label": "Weight",
        "value": "384.8 g"
      },
      {
        "label": "In the box",
        "value": "Smart Case, USB-C cable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/airpods-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/airpods-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/airpods-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/airpods-max-1.webp",
        "https://media.nexusohm.com/products/airpods-max-2.webp",
        "https://media.nexusohm.com/products/airpods-max-3.webp",
        "https://media.nexusohm.com/products/airpods-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "macbook-pro",
    "sku": "APL-MBP16-102",
    "brand": "APPLE",
    "title": "MacBook Pro 16\" M5 Pro",
    "category": "computing",
    "priceMinor": 249900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "rating": 4.9,
    "reviewCount": 936,
    "specsSummary": [
      "M5 Pro, 14-core",
      "Liquid Retina XDR",
      "24-hour battery"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Apple M5 Pro, 14-core CPU / 20-core GPU"
      },
      {
        "label": "Memory",
        "value": "24GB unified, up to 128GB"
      },
      {
        "label": "Storage",
        "value": "512GB SSD, up to 8TB"
      },
      {
        "label": "Display",
        "value": "16.2in Liquid Retina XDR, 3456×2234, 120Hz"
      },
      {
        "label": "Brightness",
        "value": "1000 nits sustained, 1600 nits peak HDR"
      },
      {
        "label": "Battery",
        "value": "Up to 24 hours video playback"
      },
      {
        "label": "Ports",
        "value": "3× Thunderbolt 5, HDMI, SDXC, MagSafe 3"
      },
      {
        "label": "Weight",
        "value": "2.14 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/macbook-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/macbook-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/macbook-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/macbook-pro-1.webp",
        "https://media.nexusohm.com/products/macbook-pro-2.webp",
        "https://media.nexusohm.com/products/macbook-pro-3.webp",
        "https://media.nexusohm.com/products/macbook-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "watch-ultra",
    "sku": "APL-AWU3-103",
    "brand": "APPLE",
    "title": "Apple Watch Ultra 3",
    "category": "computing",
    "priceMinor": 79900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 7,
    "rating": 4.8,
    "reviewCount": 2104,
    "specsSummary": [
      "49mm titanium",
      "Dual-frequency GPS",
      "100m water resistance"
    ],
    "specs": [
      {
        "label": "Case",
        "value": "49mm aerospace-grade titanium"
      },
      {
        "label": "Display",
        "value": "LTPO3 OLED, 3000 nits peak"
      },
      {
        "label": "Water resistance",
        "value": "100m, EN13319 dive certified"
      },
      {
        "label": "GPS",
        "value": "Precision dual-frequency L1 + L5"
      },
      {
        "label": "Battery",
        "value": "36 hours normal, 72 hours low power"
      },
      {
        "label": "Sensors",
        "value": "ECG, blood oxygen, temperature, depth"
      },
      {
        "label": "Durability",
        "value": "MIL-STD-810H"
      },
      {
        "label": "Connectivity",
        "value": "5G cellular, Wi-Fi 6, Bluetooth 5.3"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/watch-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/watch-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/watch-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/watch-ultra-1.webp",
        "https://media.nexusohm.com/products/watch-ultra-2.webp",
        "https://media.nexusohm.com/products/watch-ultra-3.webp",
        "https://media.nexusohm.com/products/watch-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "galaxy-s26",
    "sku": "SAM-S26U-104",
    "brand": "SAMSUNG",
    "title": "Galaxy S26",
    "category": "phones",
    "priceMinor": 89999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 41,
    "badge": "NEW_DROP",
    "rating": 4.6,
    "reviewCount": 3277,
    "specsSummary": [
      "200MP main camera",
      "6.9\" QHD+ AMOLED",
      "Titanium frame"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.9in QHD+ Dynamic AMOLED 2X, 1–120Hz"
      },
      {
        "label": "Processor",
        "value": "Snapdragon 8 Elite for Galaxy"
      },
      {
        "label": "Main camera",
        "value": "200MP wide, f/1.7, OIS"
      },
      {
        "label": "Zoom",
        "value": "5× optical periscope, 100× Space Zoom"
      },
      {
        "label": "Memory",
        "value": "12GB RAM, 256GB–1TB storage"
      },
      {
        "label": "Battery",
        "value": "5000mAh, 45W wired, 15W wireless"
      },
      {
        "label": "Build",
        "value": "Titanium frame, Gorilla Armor 2"
      },
      {
        "label": "Water resistance",
        "value": "IP68"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-s26-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-s26-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-s26-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-s26-1.webp",
        "https://media.nexusohm.com/products/galaxy-s26-2.webp",
        "https://media.nexusohm.com/products/galaxy-s26-3.webp",
        "https://media.nexusohm.com/products/galaxy-s26-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "galaxy-buds",
    "sku": "SAM-BUD4-105",
    "brand": "SAMSUNG",
    "title": "Galaxy Buds4 Pro",
    "category": "audio",
    "priceMinor": 24900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 63,
    "rating": 4.4,
    "reviewCount": 1520,
    "specsSummary": [
      "24-bit Hi-Fi",
      "Adaptive ANC",
      "IPX7"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "2-way, 10.5mm woofer + 6.1mm tweeter"
      },
      {
        "label": "Codec",
        "value": "24-bit Hi-Fi, SSC UHQ, AAC, SBC"
      },
      {
        "label": "Noise control",
        "value": "Adaptive ANC with voice detect"
      },
      {
        "label": "Battery",
        "value": "6h buds, 30h with case"
      },
      {
        "label": "Water resistance",
        "value": "IPX7"
      },
      {
        "label": "Microphones",
        "value": "3 mics per bud with VPU"
      },
      {
        "label": "Charging",
        "value": "USB-C, Qi wireless"
      },
      {
        "label": "Weight",
        "value": "5.5 g per bud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-buds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-buds-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-buds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-buds-1.webp",
        "https://media.nexusohm.com/products/galaxy-buds-2.webp",
        "https://media.nexusohm.com/products/galaxy-buds-3.webp",
        "https://media.nexusohm.com/products/galaxy-buds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "odyssey-oled",
    "sku": "SAM-G95-106",
    "brand": "SAMSUNG",
    "title": "Odyssey OLED G9 49\"",
    "category": "peripherals",
    "priceMinor": 159900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 5,
    "rating": 4.7,
    "reviewCount": 412,
    "specsSummary": [
      "5120 × 1440 OLED",
      "240Hz, 0.03ms",
      "Dual QHD ultrawide"
    ],
    "specs": [
      {
        "label": "Panel",
        "value": "49in QD-OLED, 1800R curve"
      },
      {
        "label": "Resolution",
        "value": "5120 × 1440 (Dual QHD)"
      },
      {
        "label": "Refresh",
        "value": "240Hz, 0.03ms GtG"
      },
      {
        "label": "HDR",
        "value": "VESA DisplayHDR True Black 400"
      },
      {
        "label": "Colour",
        "value": "99% DCI-P3"
      },
      {
        "label": "Ports",
        "value": "DisplayPort 1.4, 2× HDMI 2.1, USB hub"
      },
      {
        "label": "Sync",
        "value": "AMD FreeSync Premium Pro"
      },
      {
        "label": "Stand",
        "value": "Height, tilt and swivel adjustable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/odyssey-oled-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/odyssey-oled-2.webp",
      "thumb": "https://media.nexusohm.com/products/odyssey-oled-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/odyssey-oled-1.webp",
        "https://media.nexusohm.com/products/odyssey-oled-2.webp",
        "https://media.nexusohm.com/products/odyssey-oled-3.webp",
        "https://media.nexusohm.com/products/odyssey-oled-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "wh1000xm6",
    "sku": "SNY-XM6-107",
    "brand": "SONY",
    "title": "WH-1000XM6 Wireless",
    "category": "audio",
    "priceMinor": 44900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 48,
    "rating": 4.8,
    "reviewCount": 6214,
    "specsSummary": [
      "Industry-leading ANC",
      "30-hour playback",
      "LDAC Hi-Res"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "30mm carbon fibre composite"
      },
      {
        "label": "Processor",
        "value": "HD Noise Cancelling QN3"
      },
      {
        "label": "Battery",
        "value": "30 hours ANC on, 3 min quick charge = 3h"
      },
      {
        "label": "Codec",
        "value": "LDAC, AAC, SBC, Hi-Res Wireless"
      },
      {
        "label": "Frequency",
        "value": "4Hz – 40,000Hz"
      },
      {
        "label": "Microphones",
        "value": "8 mics for calls and ANC"
      },
      {
        "label": "Features",
        "value": "Speak-to-Chat, adaptive sound control"
      },
      {
        "label": "Weight",
        "value": "250 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/wh1000xm6-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/wh1000xm6-2.webp",
      "thumb": "https://media.nexusohm.com/products/wh1000xm6-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/wh1000xm6-1.webp",
        "https://media.nexusohm.com/products/wh1000xm6-2.webp",
        "https://media.nexusohm.com/products/wh1000xm6-3.webp",
        "https://media.nexusohm.com/products/wh1000xm6-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "alpha-7cr",
    "sku": "SNY-A7CR-108",
    "brand": "SONY",
    "title": "Alpha 7CR Full-Frame",
    "category": "imaging",
    "priceMinor": 289900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 8,
    "rating": 4.8,
    "reviewCount": 574,
    "specsSummary": [
      "61MP full-frame",
      "8-stop stabilisation",
      "AI subject tracking"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "61MP full-frame Exmor R BSI CMOS"
      },
      {
        "label": "Processor",
        "value": "BIONZ XR with AI unit"
      },
      {
        "label": "Stabilisation",
        "value": "5-axis in-body, 8 stops"
      },
      {
        "label": "Autofocus",
        "value": "693 phase-detect points, AI subject recognition"
      },
      {
        "label": "ISO",
        "value": "100–32000, expandable 50–102400"
      },
      {
        "label": "Video",
        "value": "4K60 with Super35 crop, 10-bit 4:2:2"
      },
      {
        "label": "Viewfinder",
        "value": "2.36M-dot OLED"
      },
      {
        "label": "Weight",
        "value": "515 g with battery"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/alpha-7cr-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/alpha-7cr-2.webp",
      "thumb": "https://media.nexusohm.com/products/alpha-7cr-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/alpha-7cr-1.webp",
        "https://media.nexusohm.com/products/alpha-7cr-2.webp",
        "https://media.nexusohm.com/products/alpha-7cr-3.webp",
        "https://media.nexusohm.com/products/alpha-7cr-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "fx3-cinema",
    "sku": "SNY-FX3-109",
    "brand": "SONY",
    "title": "FX3 Cinema Line",
    "category": "imaging",
    "priceMinor": 389900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 3,
    "badge": "LIMITED_EDITION",
    "rating": 4.9,
    "reviewCount": 188,
    "specsSummary": [
      "4K 120p",
      "Dual base ISO",
      "Active cooling"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "10.2MP full-frame back-illuminated CMOS"
      },
      {
        "label": "Video",
        "value": "4K 120p, 10-bit 4:2:2 All-Intra"
      },
      {
        "label": "Dynamic range",
        "value": "15+ stops, S-Cinetone and S-Log3"
      },
      {
        "label": "ISO",
        "value": "Dual base ISO 800 / 12800"
      },
      {
        "label": "Cooling",
        "value": "Active fan for unlimited recording"
      },
      {
        "label": "Audio",
        "value": "XLR handle, 4-channel 24-bit"
      },
      {
        "label": "Mount",
        "value": "Sony E-mount"
      },
      {
        "label": "Weight",
        "value": "715 g body only"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/fx3-cinema-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/fx3-cinema-2.webp",
      "thumb": "https://media.nexusohm.com/products/fx3-cinema-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/fx3-cinema-1.webp",
        "https://media.nexusohm.com/products/fx3-cinema-2.webp",
        "https://media.nexusohm.com/products/fx3-cinema-3.webp",
        "https://media.nexusohm.com/products/fx3-cinema-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "qc-ultra",
    "sku": "BSE-QCU-110",
    "brand": "BOSE",
    "title": "QuietComfort Ultra",
    "category": "audio",
    "priceMinor": 42900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 27,
    "rating": 4.6,
    "reviewCount": 2891,
    "specsSummary": [
      "Immersive audio",
      "CustomTune calibration",
      "24-hour battery"
    ],
    "specs": [
      {
        "label": "Noise control",
        "value": "CustomTune adaptive ANC"
      },
      {
        "label": "Audio",
        "value": "Bose Immersive Audio with head tracking"
      },
      {
        "label": "Battery",
        "value": "24 hours, 30 without Immersive"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, AAC, SBC"
      },
      {
        "label": "Microphones",
        "value": "6-mic array with rejection"
      },
      {
        "label": "Controls",
        "value": "Capacitive strip plus buttons"
      },
      {
        "label": "Folding",
        "value": "Flat-fold with carry case"
      },
      {
        "label": "Weight",
        "value": "250 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/qc-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/qc-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/qc-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/qc-ultra-1.webp",
        "https://media.nexusohm.com/products/qc-ultra-2.webp",
        "https://media.nexusohm.com/products/qc-ultra-3.webp",
        "https://media.nexusohm.com/products/qc-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "open-earbuds",
    "sku": "BSE-UOE-111",
    "brand": "BOSE",
    "title": "Ultra Open Earbuds",
    "category": "audio",
    "priceMinor": 29900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 4.3,
    "reviewCount": 742,
    "specsSummary": [
      "Open-ear clip design",
      "OpenAudio technology",
      "IPX4"
    ],
    "specs": [
      {
        "label": "Design",
        "value": "Open-ear cuff, nothing in the canal"
      },
      {
        "label": "Audio",
        "value": "Bose OpenAudio dipole transducer"
      },
      {
        "label": "Battery",
        "value": "7.5 hours, 27 with case"
      },
      {
        "label": "Water resistance",
        "value": "IPX4"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, AAC, SBC"
      },
      {
        "label": "Controls",
        "value": "Multifunction button per bud"
      },
      {
        "label": "Fit",
        "value": "Rotating barrel, one size"
      },
      {
        "label": "Weight",
        "value": "6.5 g per bud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/open-earbuds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/open-earbuds-2.webp",
      "thumb": "https://media.nexusohm.com/products/open-earbuds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/open-earbuds-1.webp",
        "https://media.nexusohm.com/products/open-earbuds-2.webp",
        "https://media.nexusohm.com/products/open-earbuds-3.webp",
        "https://media.nexusohm.com/products/open-earbuds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "soundlink-max",
    "sku": "BSE-SLM-112",
    "brand": "BOSE",
    "title": "SoundLink Max Portable",
    "category": "audio",
    "priceMinor": 39900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 19,
    "rating": 4.7,
    "reviewCount": 1063,
    "specsSummary": [
      "20-hour battery",
      "IP67 rated",
      "Custom transducers"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "Custom transducer array with two radiators"
      },
      {
        "label": "Battery",
        "value": "20 hours"
      },
      {
        "label": "Durability",
        "value": "IP67 water and dust resistant"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, AAC, SBC"
      },
      {
        "label": "Inputs",
        "value": "Bluetooth 5.4, 3.5mm aux, USB-C"
      },
      {
        "label": "Features",
        "value": "Party and stereo pairing"
      },
      {
        "label": "Extras",
        "value": "Removable rope handle, powerbank out"
      },
      {
        "label": "Weight",
        "value": "2.1 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/soundlink-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/soundlink-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/soundlink-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/soundlink-max-1.webp",
        "https://media.nexusohm.com/products/soundlink-max-2.webp",
        "https://media.nexusohm.com/products/soundlink-max-3.webp",
        "https://media.nexusohm.com/products/soundlink-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "hd900s",
    "sku": "SEN-HD900-113",
    "brand": "SENNHEISER",
    "title": "HD 900 S Reference",
    "category": "audio",
    "priceMinor": 64900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 14,
    "badge": "NEW_DROP",
    "rating": 4.9,
    "reviewCount": 327,
    "specsSummary": [
      "Open-back dynamic",
      "4Hz – 51kHz response",
      "Detachable OFC cable"
    ],
    "specs": [
      {
        "label": "Transducer",
        "value": "38mm open-back dynamic"
      },
      {
        "label": "Frequency",
        "value": "4Hz – 51,000Hz"
      },
      {
        "label": "Impedance",
        "value": "300 ohms"
      },
      {
        "label": "THD",
        "value": "Below 0.05% at 1kHz"
      },
      {
        "label": "Cable",
        "value": "Detachable 3m OFC, balanced and 6.3mm"
      },
      {
        "label": "Earpads",
        "value": "Replaceable velour"
      },
      {
        "label": "Build",
        "value": "Machined aluminium yoke and headband"
      },
      {
        "label": "Weight",
        "value": "260 g without cable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/hd900s-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/hd900s-2.webp",
      "thumb": "https://media.nexusohm.com/products/hd900s-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/hd900s-1.webp",
        "https://media.nexusohm.com/products/hd900s-2.webp",
        "https://media.nexusohm.com/products/hd900s-3.webp",
        "https://media.nexusohm.com/products/hd900s-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      }
    ]
  },
  {
    "id": "momentum-4",
    "sku": "SEN-MOM4-114",
    "brand": "SENNHEISER",
    "title": "Momentum 4 Wireless",
    "category": "audio",
    "priceMinor": 34995,
    "currency": "USD",
    "inStock": true,
    "stockCount": 22,
    "badge": "DISCOUNT",
    "rating": 4.5,
    "reviewCount": 1489,
    "specsSummary": [
      "60-hour battery",
      "Adaptive ANC",
      "aptX Adaptive"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "42mm dynamic"
      },
      {
        "label": "Battery",
        "value": "60 hours"
      },
      {
        "label": "Noise control",
        "value": "Adaptive hybrid ANC"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, AAC, SBC"
      },
      {
        "label": "Frequency",
        "value": "6Hz – 22,000Hz"
      },
      {
        "label": "Microphones",
        "value": "4-mic beamforming"
      },
      {
        "label": "App",
        "value": "Smart Control with parametric EQ"
      },
      {
        "label": "Weight",
        "value": "293 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/momentum-4-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/momentum-4-2.webp",
      "thumb": "https://media.nexusohm.com/products/momentum-4-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/momentum-4-1.webp",
        "https://media.nexusohm.com/products/momentum-4-2.webp",
        "https://media.nexusohm.com/products/momentum-4-3.webp",
        "https://media.nexusohm.com/products/momentum-4-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "mavic-4-pro",
    "sku": "DJI-MV4-115",
    "brand": "DJI",
    "title": "Mavic 4 Pro Cine",
    "category": "imaging",
    "priceMinor": 269900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 17,
    "badge": "NEW_DROP",
    "rating": 4.9,
    "reviewCount": 631,
    "specsSummary": [
      "4/3 Hasselblad CMOS",
      "6K/60 ProRes",
      "43-minute flight"
    ],
    "specs": [
      {
        "label": "Main camera",
        "value": "4/3 CMOS Hasselblad, 100MP"
      },
      {
        "label": "Video",
        "value": "6K/60fps ProRes, 4K/120fps"
      },
      {
        "label": "Gimbal",
        "value": "3-axis with 360° infinity rotation"
      },
      {
        "label": "Flight time",
        "value": "Up to 43 minutes"
      },
      {
        "label": "Range",
        "value": "30km O4+ transmission"
      },
      {
        "label": "Obstacle sensing",
        "value": "Omnidirectional with LiDAR"
      },
      {
        "label": "Storage",
        "value": "64GB internal plus microSD"
      },
      {
        "label": "Weight",
        "value": "1063 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mavic-4-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mavic-4-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/mavic-4-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mavic-4-pro-1.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-2.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-3.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "osmo-pocket",
    "sku": "DJI-OP3-116",
    "brand": "DJI",
    "title": "Osmo Pocket 3 Creator",
    "category": "imaging",
    "priceMinor": 79900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "rating": 4.7,
    "reviewCount": 1204,
    "specsSummary": [
      "1\" CMOS sensor",
      "3-axis gimbal",
      "2\" rotating screen"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "1in CMOS, f/2.0"
      },
      {
        "label": "Video",
        "value": "4K/120fps, 10-bit D-Log M"
      },
      {
        "label": "Gimbal",
        "value": "3-axis mechanical stabilisation"
      },
      {
        "label": "Screen",
        "value": "2in rotatable OLED touchscreen"
      },
      {
        "label": "Tracking",
        "value": "ActiveTrack 6.0 with face detection"
      },
      {
        "label": "Audio",
        "value": "3-mic array, DJI Mic 2 direct connect"
      },
      {
        "label": "Battery",
        "value": "166 minutes at 1080p/24"
      },
      {
        "label": "Weight",
        "value": "179 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/osmo-pocket-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/osmo-pocket-2.webp",
      "thumb": "https://media.nexusohm.com/products/osmo-pocket-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/osmo-pocket-1.webp",
        "https://media.nexusohm.com/products/osmo-pocket-2.webp",
        "https://media.nexusohm.com/products/osmo-pocket-3.webp",
        "https://media.nexusohm.com/products/osmo-pocket-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "rs4-gimbal",
    "sku": "DJI-RS4-117",
    "brand": "DJI",
    "title": "RS 4 Pro Gimbal",
    "category": "imaging",
    "priceMinor": 86900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 9,
    "rating": 4.6,
    "reviewCount": 389,
    "specsSummary": [
      "4.5kg payload",
      "LiDAR focusing",
      "29-hour runtime"
    ],
    "specs": [
      {
        "label": "Payload",
        "value": "4.5 kg tested"
      },
      {
        "label": "Focus",
        "value": "LiDAR rangefinder with 21-point ToF"
      },
      {
        "label": "Axis",
        "value": "3-axis with automated locks"
      },
      {
        "label": "Battery",
        "value": "29 hours, 1.5h full charge"
      },
      {
        "label": "Screen",
        "value": "1.8in full-colour touchscreen"
      },
      {
        "label": "Modes",
        "value": "PF, PTF, FPV, 3D Roll 360"
      },
      {
        "label": "Mount",
        "value": "Dual-layer quick release plate"
      },
      {
        "label": "Weight",
        "value": "1.2 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/rs4-gimbal-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/rs4-gimbal-2.webp",
      "thumb": "https://media.nexusohm.com/products/rs4-gimbal-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/rs4-gimbal-1.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-2.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-3.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "mx-master",
    "sku": "LOG-MXM4-118",
    "brand": "LOGITECH",
    "title": "MX Master 4",
    "category": "peripherals",
    "priceMinor": 11900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 87,
    "rating": 4.8,
    "reviewCount": 5140,
    "specsSummary": [
      "8000 DPI Darkfield",
      "MagSpeed scrolling",
      "70-day battery"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "8000 DPI Darkfield, tracks on glass"
      },
      {
        "label": "Scrolling",
        "value": "MagSpeed electromagnetic, 1000 lines/sec"
      },
      {
        "label": "Buttons",
        "value": "7 customisable, thumb wheel"
      },
      {
        "label": "Battery",
        "value": "70 days, 1 min charge = 3 hours"
      },
      {
        "label": "Connectivity",
        "value": "Bolt USB receiver, Bluetooth, 3 devices"
      },
      {
        "label": "Software",
        "value": "Logi Options+ with per-app profiles"
      },
      {
        "label": "Flow",
        "value": "Cross-computer copy and paste"
      },
      {
        "label": "Weight",
        "value": "141 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mx-master-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mx-master-2.webp",
      "thumb": "https://media.nexusohm.com/products/mx-master-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mx-master-1.webp",
        "https://media.nexusohm.com/products/mx-master-2.webp",
        "https://media.nexusohm.com/products/mx-master-3.webp",
        "https://media.nexusohm.com/products/mx-master-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "mx-mechanical",
    "sku": "LOG-MXK-119",
    "brand": "LOGITECH",
    "title": "MX Mechanical Keyboard",
    "category": "peripherals",
    "priceMinor": 16900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 44,
    "rating": 4.6,
    "reviewCount": 2277,
    "specsSummary": [
      "Low-profile tactile",
      "Smart backlighting",
      "Multi-device Flow"
    ],
    "specs": [
      {
        "label": "Switches",
        "value": "Low-profile tactile quiet"
      },
      {
        "label": "Layout",
        "value": "Full size with numeric keypad"
      },
      {
        "label": "Backlight",
        "value": "6 patterns, proximity activated"
      },
      {
        "label": "Battery",
        "value": "15 days lit, 10 months unlit"
      },
      {
        "label": "Connectivity",
        "value": "Bolt receiver, Bluetooth, 3 devices"
      },
      {
        "label": "Compatibility",
        "value": "Windows, macOS, Linux, iPadOS, Android"
      },
      {
        "label": "Build",
        "value": "Aluminium top case"
      },
      {
        "label": "Weight",
        "value": "828 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mx-mechanical-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mx-mechanical-2.webp",
      "thumb": "https://media.nexusohm.com/products/mx-mechanical-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mx-mechanical-1.webp",
        "https://media.nexusohm.com/products/mx-mechanical-2.webp",
        "https://media.nexusohm.com/products/mx-mechanical-3.webp",
        "https://media.nexusohm.com/products/mx-mechanical-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "brio-webcam",
    "sku": "LOG-BRIO-120",
    "brand": "LOGITECH",
    "title": "Brio 4K Pro Webcam",
    "category": "imaging",
    "priceMinor": 19900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 52,
    "rating": 4.4,
    "reviewCount": 3301,
    "specsSummary": [
      "4K HDR at 30fps",
      "RightLight 5",
      "Windows Hello"
    ],
    "specs": [
      {
        "label": "Resolution",
        "value": "4K UHD 30fps, 1080p 60fps"
      },
      {
        "label": "Field of view",
        "value": "Adjustable 65°, 78°, 90°"
      },
      {
        "label": "HDR",
        "value": "RightLight 5 with HDR"
      },
      {
        "label": "Zoom",
        "value": "5× digital"
      },
      {
        "label": "Autofocus",
        "value": "Continuous with face priority"
      },
      {
        "label": "Microphones",
        "value": "Dual omnidirectional with noise reduction"
      },
      {
        "label": "Security",
        "value": "Windows Hello IR facial recognition"
      },
      {
        "label": "Mount",
        "value": "Clip plus tripod thread"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/brio-webcam-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/brio-webcam-2.webp",
      "thumb": "https://media.nexusohm.com/products/brio-webcam-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/brio-webcam-1.webp",
        "https://media.nexusohm.com/products/brio-webcam-2.webp",
        "https://media.nexusohm.com/products/brio-webcam-3.webp",
        "https://media.nexusohm.com/products/brio-webcam-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "blackwidow",
    "sku": "RZR-BW4-121",
    "brand": "RAZER",
    "title": "BlackWidow V4 Pro",
    "category": "peripherals",
    "priceMinor": 22900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 23,
    "rating": 4.5,
    "reviewCount": 1876,
    "specsSummary": [
      "Green mechanical switches",
      "Command dial",
      "Chroma RGB"
    ],
    "specs": [
      {
        "label": "Switches",
        "value": "Razer Green mechanical, 80M keystrokes"
      },
      {
        "label": "Actuation",
        "value": "1.9mm, clicky tactile"
      },
      {
        "label": "Lighting",
        "value": "Per-key Chroma RGB, underglow"
      },
      {
        "label": "Controls",
        "value": "Command dial, 4 media keys"
      },
      {
        "label": "Wrist rest",
        "value": "Magnetic plush leatherette"
      },
      {
        "label": "Polling",
        "value": "1000Hz"
      },
      {
        "label": "Build",
        "value": "5052 aluminium alloy top"
      },
      {
        "label": "Extras",
        "value": "8 dedicated macro keys"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/blackwidow-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/blackwidow-2.webp",
      "thumb": "https://media.nexusohm.com/products/blackwidow-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/blackwidow-1.webp",
        "https://media.nexusohm.com/products/blackwidow-2.webp",
        "https://media.nexusohm.com/products/blackwidow-3.webp",
        "https://media.nexusohm.com/products/blackwidow-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "viper-v3",
    "sku": "RZR-VV3-122",
    "brand": "RAZER",
    "title": "Viper V3 Pro",
    "category": "peripherals",
    "priceMinor": 15900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 4,
    "rating": 4.7,
    "reviewCount": 2043,
    "specsSummary": [
      "35K DPI Focus Pro",
      "54g chassis",
      "8000Hz polling"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "Focus Pro 35K optical"
      },
      {
        "label": "DPI",
        "value": "35,000 with 750 IPS tracking"
      },
      {
        "label": "Polling",
        "value": "8000Hz with HyperPolling dongle"
      },
      {
        "label": "Switches",
        "value": "Gen-3 optical, 90M clicks"
      },
      {
        "label": "Battery",
        "value": "95 hours at 1000Hz"
      },
      {
        "label": "Shape",
        "value": "Symmetrical right-handed"
      },
      {
        "label": "Feet",
        "value": "100% PTFE"
      },
      {
        "label": "Weight",
        "value": "54 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/viper-v3-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/viper-v3-2.webp",
      "thumb": "https://media.nexusohm.com/products/viper-v3-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/viper-v3-1.webp",
        "https://media.nexusohm.com/products/viper-v3-2.webp",
        "https://media.nexusohm.com/products/viper-v3-3.webp",
        "https://media.nexusohm.com/products/viper-v3-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "blade-16",
    "sku": "RZR-BL16-123",
    "brand": "RAZER",
    "title": "Blade 16 Creator",
    "category": "computing",
    "priceMinor": 329900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 4.4,
    "reviewCount": 517,
    "specsSummary": [
      "RTX 5090 Laptop",
      "16\" OLED 240Hz",
      "CNC aluminium unibody"
    ],
    "specs": [
      {
        "label": "GPU",
        "value": "NVIDIA GeForce RTX 5090 Laptop, 24GB"
      },
      {
        "label": "CPU",
        "value": "Intel Core Ultra 9 275HX"
      },
      {
        "label": "Display",
        "value": "16in OLED 2560×1600, 240Hz, 0.2ms"
      },
      {
        "label": "Memory",
        "value": "32GB DDR5-6400, up to 96GB"
      },
      {
        "label": "Storage",
        "value": "2TB PCIe Gen4 NVMe"
      },
      {
        "label": "Cooling",
        "value": "Vapour chamber with liquid metal"
      },
      {
        "label": "Build",
        "value": "CNC aluminium unibody"
      },
      {
        "label": "Weight",
        "value": "2.14 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/blade-16-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/blade-16-2.webp",
      "thumb": "https://media.nexusohm.com/products/blade-16-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/blade-16-1.webp",
        "https://media.nexusohm.com/products/blade-16-2.webp",
        "https://media.nexusohm.com/products/blade-16-3.webp",
        "https://media.nexusohm.com/products/blade-16-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "prime-powerbank",
    "sku": "ANK-P27-124",
    "brand": "ANKER",
    "title": "Prime 27,650mAh Bank",
    "category": "computing",
    "priceMinor": 17900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 96,
    "rating": 4.6,
    "reviewCount": 4412,
    "specsSummary": [
      "250W total output",
      "Smart display",
      "Three-device charging"
    ],
    "specs": [
      {
        "label": "Capacity",
        "value": "27,650mAh / 99.54Wh"
      },
      {
        "label": "Output",
        "value": "250W total across three ports"
      },
      {
        "label": "Ports",
        "value": "2× USB-C 140W, 1× USB-A 65W"
      },
      {
        "label": "Recharge",
        "value": "Full in 70 minutes at 170W"
      },
      {
        "label": "Display",
        "value": "Smart LCD with per-port wattage"
      },
      {
        "label": "Safety",
        "value": "ActiveShield 3.0 temperature monitoring"
      },
      {
        "label": "Airline",
        "value": "Under the 100Wh carry-on limit"
      },
      {
        "label": "Weight",
        "value": "1.4 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/prime-powerbank-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/prime-powerbank-2.webp",
      "thumb": "https://media.nexusohm.com/products/prime-powerbank-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/prime-powerbank-1.webp",
        "https://media.nexusohm.com/products/prime-powerbank-2.webp",
        "https://media.nexusohm.com/products/prime-powerbank-3.webp",
        "https://media.nexusohm.com/products/prime-powerbank-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "soundcore-liberty",
    "sku": "ANK-SCL5-125",
    "brand": "ANKER",
    "title": "Soundcore Liberty 5",
    "category": "audio",
    "priceMinor": 12999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 110,
    "badge": "DISCOUNT",
    "rating": 4.3,
    "reviewCount": 6820,
    "specsSummary": [
      "Adaptive ANC 3.0",
      "48-hour total",
      "LDAC Hi-Res"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "10mm dual dynamic with dual chamber"
      },
      {
        "label": "Noise control",
        "value": "Adaptive ANC 3.0, 98.5% reduction"
      },
      {
        "label": "Battery",
        "value": "8h buds, 48h with case"
      },
      {
        "label": "Codec",
        "value": "LDAC Hi-Res Wireless, AAC, SBC"
      },
      {
        "label": "Microphones",
        "value": "6 mics with AI wind reduction"
      },
      {
        "label": "Water resistance",
        "value": "IPX4"
      },
      {
        "label": "Charging",
        "value": "USB-C and wireless"
      },
      {
        "label": "App",
        "value": "HearID personalised EQ"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/soundcore-liberty-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/soundcore-liberty-2.webp",
      "thumb": "https://media.nexusohm.com/products/soundcore-liberty-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/soundcore-liberty-1.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-2.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-3.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "gan-charger",
    "sku": "ANK-747-126",
    "brand": "ANKER",
    "title": "Prime 250W GaN Charger",
    "category": "computing",
    "priceMinor": 14900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 71,
    "rating": 4.7,
    "reviewCount": 1955,
    "specsSummary": [
      "Six ports, 250W",
      "ActiveShield 3.0",
      "Desktop form factor"
    ],
    "specs": [
      {
        "label": "Output",
        "value": "250W total"
      },
      {
        "label": "Ports",
        "value": "4× USB-C, 2× USB-A"
      },
      {
        "label": "Fast charge",
        "value": "140W single port PD 3.1"
      },
      {
        "label": "Technology",
        "value": "GaN III, 40% smaller than silicon"
      },
      {
        "label": "Display",
        "value": "Power distribution readout"
      },
      {
        "label": "Safety",
        "value": "ActiveShield 3.0"
      },
      {
        "label": "Input",
        "value": "100–240V worldwide"
      },
      {
        "label": "Form",
        "value": "Desktop with detachable cord"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/gan-charger-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/gan-charger-2.webp",
      "thumb": "https://media.nexusohm.com/products/gan-charger-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/gan-charger-1.webp",
        "https://media.nexusohm.com/products/gan-charger-2.webp",
        "https://media.nexusohm.com/products/gan-charger-3.webp",
        "https://media.nexusohm.com/products/gan-charger-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "phone-3a",
    "sku": "NTH-P3A-127",
    "brand": "NOTHING",
    "title": "Phone (3a) Pro",
    "category": "phones",
    "priceMinor": 47900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 38,
    "rating": 4.5,
    "reviewCount": 1207,
    "specsSummary": [
      "6.7\" LTPO AMOLED",
      "Glyph interface",
      "5000mAh"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.7in LTPO AMOLED, 1–120Hz, 3000 nits"
      },
      {
        "label": "Processor",
        "value": "Snapdragon 7s Gen 3"
      },
      {
        "label": "Camera",
        "value": "50MP main + 50MP periscope + 8MP ultrawide"
      },
      {
        "label": "Glyph",
        "value": "Glyph Matrix rear LED interface"
      },
      {
        "label": "Memory",
        "value": "12GB RAM, 256GB storage"
      },
      {
        "label": "Battery",
        "value": "5000mAh, 50W wired"
      },
      {
        "label": "Software",
        "value": "Nothing OS 3, 3 years of upgrades"
      },
      {
        "label": "Build",
        "value": "Transparent back, IP64"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/phone-3a-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/phone-3a-2.webp",
      "thumb": "https://media.nexusohm.com/products/phone-3a-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/phone-3a-1.webp",
        "https://media.nexusohm.com/products/phone-3a-2.webp",
        "https://media.nexusohm.com/products/phone-3a-3.webp",
        "https://media.nexusohm.com/products/phone-3a-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "ear-open",
    "sku": "NTH-EAR-128",
    "brand": "NOTHING",
    "title": "Ear (Open)",
    "category": "audio",
    "priceMinor": 14900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 4.4,
    "reviewCount": 412,
    "specsSummary": [
      "Open-ear driver",
      "IP54 rated",
      "38-hour case"
    ],
    "specs": [
      {
        "label": "Design",
        "value": "Open-ear, ear-hook fit"
      },
      {
        "label": "Driver",
        "value": "14.2mm custom dynamic"
      },
      {
        "label": "Battery",
        "value": "8h buds, 30h with case"
      },
      {
        "label": "Water resistance",
        "value": "IP54"
      },
      {
        "label": "Codec",
        "value": "AAC, SBC"
      },
      {
        "label": "Microphones",
        "value": "3 mics with Clear Voice"
      },
      {
        "label": "Controls",
        "value": "Pinch and slide"
      },
      {
        "label": "Weight",
        "value": "8.1 g per bud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/ear-open-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/ear-open-2.webp",
      "thumb": "https://media.nexusohm.com/products/ear-open-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/ear-open-1.webp",
        "https://media.nexusohm.com/products/ear-open-2.webp",
        "https://media.nexusohm.com/products/ear-open-3.webp",
        "https://media.nexusohm.com/products/ear-open-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "cmf-buds",
    "sku": "NTH-CMF-129",
    "brand": "NOTHING",
    "title": "CMF Buds Pro 3",
    "category": "audio",
    "priceMinor": 6900,
    "currency": "USD",
    "inStock": false,
    "stockCount": 0,
    "rating": 4.1,
    "reviewCount": 883,
    "specsSummary": [
      "50dB hybrid ANC",
      "Smart dial case",
      "43-hour total"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "11mm bio-fibre dynamic"
      },
      {
        "label": "Noise control",
        "value": "Hybrid ANC up to 50dB"
      },
      {
        "label": "Battery",
        "value": "10h buds, 43h with case"
      },
      {
        "label": "Case",
        "value": "Smart Dial for volume and tracks"
      },
      {
        "label": "Codec",
        "value": "LDAC, AAC, SBC"
      },
      {
        "label": "Water resistance",
        "value": "IP55"
      },
      {
        "label": "Microphones",
        "value": "6 mics with Clear Voice"
      },
      {
        "label": "Weight",
        "value": "4.9 g per bud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/cmf-buds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/cmf-buds-2.webp",
      "thumb": "https://media.nexusohm.com/products/cmf-buds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/cmf-buds-1.webp",
        "https://media.nexusohm.com/products/cmf-buds-2.webp",
        "https://media.nexusohm.com/products/cmf-buds-3.webp",
        "https://media.nexusohm.com/products/cmf-buds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      }
    ]
  },
  {
    "id": "q3-max",
    "sku": "KEY-Q3M-130",
    "brand": "KEYCHRON",
    "title": "Q3 Max QMK Custom",
    "category": "peripherals",
    "priceMinor": 21900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 34,
    "badge": "NEW_DROP",
    "rating": 4.8,
    "reviewCount": 743,
    "specsSummary": [
      "Gasket mount",
      "QMK / VIA",
      "2.4G and Bluetooth"
    ],
    "specs": [
      {
        "label": "Mount",
        "value": "Double gasket with silicone pads"
      },
      {
        "label": "Switches",
        "value": "Hot-swappable, 3-pin and 5-pin"
      },
      {
        "label": "Firmware",
        "value": "QMK and VIA, fully remappable"
      },
      {
        "label": "Connectivity",
        "value": "2.4GHz, Bluetooth 5.1, USB-C"
      },
      {
        "label": "Battery",
        "value": "4000mAh, up to 100 hours"
      },
      {
        "label": "Case",
        "value": "CNC machined 6063 aluminium"
      },
      {
        "label": "Keycaps",
        "value": "Double-shot PBT, OSA profile"
      },
      {
        "label": "Weight",
        "value": "1.9 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/q3-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/q3-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/q3-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/q3-max-1.webp",
        "https://media.nexusohm.com/products/q3-max-2.webp",
        "https://media.nexusohm.com/products/q3-max-3.webp",
        "https://media.nexusohm.com/products/q3-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "switch-set",
    "sku": "KEY-NBS-131",
    "brand": "KEYCHRON",
    "title": "Nebula Switch Set ×110",
    "category": "peripherals",
    "priceMinor": 6900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 210,
    "rating": 4.5,
    "reviewCount": 318,
    "specsSummary": [
      "45gf linear",
      "Factory lubed",
      "1.9mm pre-travel"
    ],
    "specs": [
      {
        "label": "Type",
        "value": "Linear"
      },
      {
        "label": "Actuation force",
        "value": "45 gf"
      },
      {
        "label": "Pre-travel",
        "value": "1.9 mm"
      },
      {
        "label": "Total travel",
        "value": "3.5 mm"
      },
      {
        "label": "Lubrication",
        "value": "Factory lubed stem and spring"
      },
      {
        "label": "Housing",
        "value": "Polycarbonate top, nylon bottom"
      },
      {
        "label": "Pins",
        "value": "5-pin PCB mount"
      },
      {
        "label": "Quantity",
        "value": "110 switches"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/switch-set-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/switch-set-2.webp",
      "thumb": "https://media.nexusohm.com/products/switch-set-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/switch-set-1.webp",
        "https://media.nexusohm.com/products/switch-set-2.webp",
        "https://media.nexusohm.com/products/switch-set-3.webp",
        "https://media.nexusohm.com/products/switch-set-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Nebula Violet",
        "hex": "#5B3BFF"
      }
    ]
  },
  {
    "id": "k-pro-mouse",
    "sku": "KEY-M6-132",
    "brand": "KEYCHRON",
    "title": "M6 Wireless Mouse",
    "category": "peripherals",
    "priceMinor": 8900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 28,
    "rating": 4.2,
    "reviewCount": 214,
    "specsSummary": [
      "26K DPI PixArt",
      "1000Hz polling",
      "70g chassis"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "PixArt PAW3395 optical"
      },
      {
        "label": "DPI",
        "value": "26,000 adjustable in 50 steps"
      },
      {
        "label": "Polling",
        "value": "1000Hz wired, 1000Hz 2.4GHz"
      },
      {
        "label": "Switches",
        "value": "Optical, 80M clicks"
      },
      {
        "label": "Connectivity",
        "value": "2.4GHz, Bluetooth 5.1, USB-C"
      },
      {
        "label": "Battery",
        "value": "500mAh, up to 70 hours"
      },
      {
        "label": "Software",
        "value": "Keychron Launcher, browser based"
      },
      {
        "label": "Weight",
        "value": "70 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/k-pro-mouse-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/k-pro-mouse-2.webp",
      "thumb": "https://media.nexusohm.com/products/k-pro-mouse-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/k-pro-mouse-1.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-2.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-3.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "op1-field",
    "sku": "TE-OP1F-133",
    "brand": "TEENAGE_ENGINEERING",
    "title": "OP-1 Field Synthesizer",
    "category": "audio",
    "priceMinor": 199900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "badge": "LIMITED_EDITION",
    "rating": 4.9,
    "reviewCount": 128,
    "specsSummary": [
      "32-bit audio engine",
      "24-hour battery",
      "Bluetooth MIDI"
    ],
    "specs": [
      {
        "label": "Engine",
        "value": "32-bit audio throughout"
      },
      {
        "label": "Battery",
        "value": "16 hours continuous"
      },
      {
        "label": "Connectivity",
        "value": "Bluetooth MIDI, USB-C audio interface"
      },
      {
        "label": "Keys",
        "value": "24 keys, velocity sensitive"
      },
      {
        "label": "Synthesis",
        "value": "12 engines including Dimension and Digital"
      },
      {
        "label": "Effects",
        "value": "8 effects, 2 send slots"
      },
      {
        "label": "Tape",
        "value": "4-track tape with 6 reels"
      },
      {
        "label": "Build",
        "value": "Aluminium unibody, 1.1 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/op1-field-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/op1-field-2.webp",
      "thumb": "https://media.nexusohm.com/products/op1-field-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/op1-field-1.webp",
        "https://media.nexusohm.com/products/op1-field-2.webp",
        "https://media.nexusohm.com/products/op1-field-3.webp",
        "https://media.nexusohm.com/products/op1-field-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "tp7-recorder",
    "sku": "TE-TP7-134",
    "brand": "TEENAGE_ENGINEERING",
    "title": "TP-7 Field Recorder",
    "category": "audio",
    "priceMinor": 149900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 7,
    "rating": 4.7,
    "reviewCount": 203,
    "specsSummary": [
      "96kHz / 32-bit",
      "Motorised reel",
      "Three USB-C inputs"
    ],
    "specs": [
      {
        "label": "Recording",
        "value": "96kHz / 32-bit float"
      },
      {
        "label": "Storage",
        "value": "128GB internal"
      },
      {
        "label": "Reel",
        "value": "Motorised tape reel for scrubbing"
      },
      {
        "label": "Inputs",
        "value": "3× USB-C, 3.5mm mic in"
      },
      {
        "label": "Microphone",
        "value": "Built-in omnidirectional"
      },
      {
        "label": "Battery",
        "value": "7 hours continuous"
      },
      {
        "label": "Transcription",
        "value": "Via field companion app"
      },
      {
        "label": "Build",
        "value": "Machined aluminium, 90 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/tp7-recorder-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/tp7-recorder-2.webp",
      "thumb": "https://media.nexusohm.com/products/tp7-recorder-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/tp7-recorder-1.webp",
        "https://media.nexusohm.com/products/tp7-recorder-2.webp",
        "https://media.nexusohm.com/products/tp7-recorder-3.webp",
        "https://media.nexusohm.com/products/tp7-recorder-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "ob4-speaker",
    "sku": "TE-OB4-135",
    "brand": "TEENAGE_ENGINEERING",
    "title": "OB-4 Magic Radio",
    "category": "audio",
    "priceMinor": 64900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 11,
    "rating": 4.6,
    "reviewCount": 176,
    "specsSummary": [
      "Always-on recording",
      "4\" bass drivers",
      "20-hour battery"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "2× 4in bass, 2× tweeters"
      },
      {
        "label": "Recording",
        "value": "Always-on 2-hour rolling buffer"
      },
      {
        "label": "Sources",
        "value": "FM radio, Bluetooth, aux"
      },
      {
        "label": "Battery",
        "value": "Up to 20 hours"
      },
      {
        "label": "Controls",
        "value": "Motorised tape wheel for scrubbing"
      },
      {
        "label": "Display",
        "value": "Dot-matrix LED"
      },
      {
        "label": "Build",
        "value": "Aluminium with rubber bumpers"
      },
      {
        "label": "Weight",
        "value": "3.2 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/ob4-speaker-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/ob4-speaker-2.webp",
      "thumb": "https://media.nexusohm.com/products/ob4-speaker-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/ob4-speaker-1.webp",
        "https://media.nexusohm.com/products/ob4-speaker-2.webp",
        "https://media.nexusohm.com/products/ob4-speaker-3.webp",
        "https://media.nexusohm.com/products/ob4-speaker-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  }
]

/** The hero's featured drop. */
export const featuredDrop: Product = products.find((p) => p.sku === 'DJI-MV4-115')!
