// GENERATED by scripts/build-catalog.mjs from D1. Do not edit by hand.
// The database is the source of truth; this file is the build-time snapshot
// that lets the storefront render its first paint without the API.
//
// Row order is the catalogue's display order and is rendered as-is by the
// shop page, so it is behaviour. It comes from products.display_order.
import type { Product } from '@/types'

export const products: Product[] = [
  {
    "id": "iphone-18-pro",
    "sku": "APL-IP18P-256",
    "brand": "APPLE",
    "title": "iPhone 18 Pro",
    "category": "phones",
    "priceMinor": 119900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 48,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "48MP triple Fusion camera",
      "A20 Pro chip",
      "Up to 36h video playback"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.3in Super Retina XDR OLED, 2622×1206, ProMotion up to 120Hz, 3,000 nits outdoor"
      },
      {
        "label": "Chip",
        "value": "A20 Pro, 6-core CPU (2 super + 4 efficiency), 7-core GPU"
      },
      {
        "label": "Neural Engine",
        "value": "Dual 16-core"
      },
      {
        "label": "Rear cameras",
        "value": "48MP Fusion main f/1.48–f/4.0, 48MP ultra wide f/2.2, 48MP 4× telephoto f/2.8"
      },
      {
        "label": "Front camera",
        "value": "18MP Center Stage f/1.9"
      },
      {
        "label": "Battery",
        "value": "Up to 36 hours video playback"
      },
      {
        "label": "Charging",
        "value": "Up to 50% in about 15 min with a 60W adapter; MagSafe and Qi2 up to 25W"
      },
      {
        "label": "Storage",
        "value": "256GB / 512GB / 1TB / 2TB"
      },
      {
        "label": "SIM",
        "value": "Nano-SIM and eSIM (Malaysian model)"
      },
      {
        "label": "Build",
        "value": "Aluminium unibody, IP68 (6 m for 30 min)"
      },
      {
        "label": "Size and weight",
        "value": "150.0 × 71.9 × 8.75 mm, 211 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/iphone-18-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/iphone-18-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/iphone-18-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/iphone-18-pro-1.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-2.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-3.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Burgundy",
        "hex": "#6E2639"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Glacier",
        "hex": "#BFD4E4"
      }
    ]
  },
  {
    "id": "iphone-18-pro-max",
    "sku": "APL-IP18PM-256",
    "brand": "APPLE",
    "title": "iPhone 18 Pro Max",
    "category": "phones",
    "priceMinor": 129900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "48MP triple Fusion camera",
      "6.9\" ProMotion display",
      "Up to 45h video playback"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.9in Super Retina XDR OLED, 2868×1320, ProMotion up to 120Hz, 3,000 nits outdoor"
      },
      {
        "label": "Chip",
        "value": "A20 Pro, 6-core CPU (2 super + 4 efficiency), 7-core GPU"
      },
      {
        "label": "Neural Engine",
        "value": "Dual 16-core"
      },
      {
        "label": "Rear cameras",
        "value": "48MP Fusion main f/1.48–f/4.0, 48MP ultra wide f/2.2, 48MP 4× telephoto f/2.8"
      },
      {
        "label": "Front camera",
        "value": "18MP Center Stage f/1.9"
      },
      {
        "label": "Battery",
        "value": "Up to 45 hours video playback"
      },
      {
        "label": "Charging",
        "value": "Up to 50% in about 15 min with a 60W adapter; MagSafe and Qi2 up to 25W"
      },
      {
        "label": "Storage",
        "value": "256GB / 512GB / 1TB / 2TB"
      },
      {
        "label": "SIM",
        "value": "Nano-SIM and eSIM (Malaysian model)"
      },
      {
        "label": "Build",
        "value": "Aluminium unibody, IP68 (6 m for 30 min)"
      },
      {
        "label": "Size and weight",
        "value": "163.4 × 78.0 × 8.75 mm, 249 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/iphone-18-pro-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/iphone-18-pro-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/iphone-18-pro-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/iphone-18-pro-max-1.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-2.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-3.webp",
        "https://media.nexusohm.com/products/iphone-18-pro-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Burgundy",
        "hex": "#6E2639"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Glacier",
        "hex": "#BFD4E4"
      }
    ]
  },
  {
    "id": "galaxy-s26-ultra",
    "sku": "SAM-S26U-256",
    "brand": "SAMSUNG",
    "title": "Galaxy S26 Ultra",
    "category": "phones",
    "priceMinor": 129999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 42,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "6.9\" QHD+ 120Hz display",
      "200MP f/1.4 main camera",
      "60W wired, 25W wireless"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.9in QHD+ Dynamic AMOLED 2X, 3120×1440, 1–120Hz adaptive, 2,600 nits"
      },
      {
        "label": "Privacy",
        "value": "Built-in Privacy Display"
      },
      {
        "label": "Chip",
        "value": "Snapdragon 8 Elite Gen 5 for Galaxy"
      },
      {
        "label": "Memory",
        "value": "12GB RAM with 256GB or 512GB, 16GB RAM with 1TB"
      },
      {
        "label": "Rear cameras",
        "value": "200MP wide f/1.4, 50MP ultrawide f/1.9, 50MP 5× telephoto f/2.9, 10MP 3× telephoto f/2.4"
      },
      {
        "label": "Zoom",
        "value": "Up to 100× Space Zoom"
      },
      {
        "label": "Front camera",
        "value": "12MP f/2.2"
      },
      {
        "label": "Battery",
        "value": "5,000mAh, up to 31 hours video playback"
      },
      {
        "label": "Charging",
        "value": "60W wired (up to 75% in about 30 min), 25W wireless"
      },
      {
        "label": "Build",
        "value": "Armor Aluminum frame, Corning Gorilla Armor 2, IP68"
      },
      {
        "label": "Size and weight",
        "value": "163.6 × 78.1 × 7.9 mm, 214 g"
      },
      {
        "label": "S Pen",
        "value": "Built in"
      },
      {
        "label": "Software",
        "value": "Android 16, One UI 8.5"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-s26-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-s26-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-s26-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-s26-ultra-1.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-2.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-3.webp",
        "https://media.nexusohm.com/products/galaxy-s26-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Cobalt Violet",
        "hex": "#4B4A8F"
      },
      {
        "name": "Sky Blue",
        "hex": "#9FC4E2"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "pixel-11-pro",
    "sku": "GGL-P11P-256",
    "brand": "GOOGLE",
    "title": "Pixel 11 Pro",
    "category": "phones",
    "priceMinor": 109900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 37,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Google Tensor G6",
      "50MP + 48MP 5× telephoto",
      "7 years of updates"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.3in Super Actua LTPO OLED, 2856×1280, 1–120Hz, 3,600 nits peak"
      },
      {
        "label": "Chip",
        "value": "Google Tensor G6, Titan M3 security"
      },
      {
        "label": "Memory",
        "value": "12GB RAM with 256GB, 16GB RAM with 512GB or 1TB"
      },
      {
        "label": "Rear cameras",
        "value": "50MP wide f/1.68, 48MP ultrawide f/1.7, 48MP 5× telephoto f/2.8"
      },
      {
        "label": "Zoom",
        "value": "Pro Zoom up to 120×"
      },
      {
        "label": "Front camera",
        "value": "42MP with autofocus, f/2.2"
      },
      {
        "label": "Battery",
        "value": "4,850mAh typical"
      },
      {
        "label": "Charging",
        "value": "30W wired (up to 55% in about 30 min), 25W wireless"
      },
      {
        "label": "Durability",
        "value": "IP68"
      },
      {
        "label": "Size and weight",
        "value": "152.7 × 71.9 × 8.4 mm, 204 g"
      },
      {
        "label": "Software",
        "value": "Android 17, 7 years of OS and security updates"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/pixel-11-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/pixel-11-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/pixel-11-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/pixel-11-pro-1.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-2.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-3.webp",
        "https://media.nexusohm.com/products/pixel-11-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Porcelain",
        "hex": "#E6E0D6"
      },
      {
        "name": "Jade",
        "hex": "#3E6B5A"
      }
    ]
  },
  {
    "id": "oneplus-15",
    "sku": "OPO-15-256",
    "brand": "ONEPLUS",
    "title": "OnePlus 15",
    "category": "phones",
    "priceMinor": 89999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 55,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "7,300mAh battery",
      "165Hz 1.5K LTPO display",
      "120W wired, 50W wireless"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.78in 1.5K LTPO AMOLED, 2772×1272, up to 165Hz in games (1–120Hz otherwise), 1,800 nits"
      },
      {
        "label": "Glass",
        "value": "Corning Gorilla Glass Victus 2"
      },
      {
        "label": "Chip",
        "value": "Snapdragon 8 Elite Gen 5"
      },
      {
        "label": "Memory",
        "value": "12GB RAM with 256GB, 16GB RAM with 512GB"
      },
      {
        "label": "Rear cameras",
        "value": "50MP main with OIS, 50MP ultrawide with autofocus, 50MP 3.5× periscope telephoto"
      },
      {
        "label": "Front camera",
        "value": "32MP"
      },
      {
        "label": "Battery",
        "value": "7,300mAh Silicon NanoStack"
      },
      {
        "label": "Charging",
        "value": "120W wired (80W in the US and Canada), 50W wireless"
      },
      {
        "label": "Durability",
        "value": "IP66, IP68, IP69 and IP69K"
      },
      {
        "label": "Weight",
        "value": "211–215 g, by colour"
      },
      {
        "label": "Software",
        "value": "OxygenOS 16, Android 16"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/oneplus-15-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/oneplus-15-2.webp",
      "thumb": "https://media.nexusohm.com/products/oneplus-15-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/oneplus-15-1.webp",
        "https://media.nexusohm.com/products/oneplus-15-2.webp",
        "https://media.nexusohm.com/products/oneplus-15-3.webp",
        "https://media.nexusohm.com/products/oneplus-15-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Cobalt Violet",
        "hex": "#4B4A8F"
      },
      {
        "name": "Sand Storm",
        "hex": "#C2A878"
      }
    ]
  },
  {
    "id": "xiaomi-17-ultra",
    "sku": "XMI-17U-512",
    "brand": "XIAOMI",
    "title": "Xiaomi 17 Ultra",
    "category": "phones",
    "priceMinor": 129900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 22,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "1-inch Leica main camera",
      "200MP 75–100mm telephoto",
      "6,000mAh, 90W charging"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.9in HyperRGB OLED, 2608×1200, 1–120Hz, 3,500 nits peak"
      },
      {
        "label": "Chip",
        "value": "Snapdragon 8 Elite Gen 5"
      },
      {
        "label": "Main camera",
        "value": "Leica 23mm, 50MP Light Fusion 1050L 1in sensor, f/1.67"
      },
      {
        "label": "Telephoto",
        "value": "Leica 200MP, 75–100mm continuous optical zoom, APO lens"
      },
      {
        "label": "Ultrawide",
        "value": "Leica 14mm"
      },
      {
        "label": "Battery",
        "value": "6,000mAh typical"
      },
      {
        "label": "Charging",
        "value": "90W wired, 50W wireless"
      },
      {
        "label": "Weight",
        "value": "From 218.4 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/xiaomi-17-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/xiaomi-17-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/xiaomi-17-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/xiaomi-17-ultra-1.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-2.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-3.webp",
        "https://media.nexusohm.com/products/xiaomi-17-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Sand Storm",
        "hex": "#C2A878"
      }
    ]
  },
  {
    "id": "xps-16",
    "sku": "DEL-XPS16-26",
    "brand": "DELL",
    "title": "XPS 16 (2026)",
    "category": "computing",
    "priceMinor": 174900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 24,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "3.2K 120Hz OLED option",
      "Intel Core Ultra Series 3",
      "From 1.65 kg"
    ],
    "specs": [
      {
        "label": "Processor",
        "value": "Intel Core Ultra 7 355, Core Ultra X7 358H or Core Ultra X9 388H"
      },
      {
        "label": "Graphics",
        "value": "Intel integrated"
      },
      {
        "label": "Display",
        "value": "16in 3.2K OLED touch, 20–120Hz, 400 nits; or 2K LCD, 1–120Hz, 500 nits"
      },
      {
        "label": "Memory",
        "value": "16GB LPDDR5x, 7467 MT/s"
      },
      {
        "label": "Storage",
        "value": "512GB to 4TB SSD"
      },
      {
        "label": "Ports",
        "value": "3× Thunderbolt 4 (USB-C) with DisplayPort 2.1 and power delivery, 3.5mm jack"
      },
      {
        "label": "Battery",
        "value": "70Wh"
      },
      {
        "label": "Weight",
        "value": "From 1.65 kg (OLED)"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/xps-16-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/xps-16-2.webp",
      "thumb": "https://media.nexusohm.com/products/xps-16-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/xps-16-1.webp",
        "https://media.nexusohm.com/products/xps-16-2.webp",
        "https://media.nexusohm.com/products/xps-16-3.webp",
        "https://media.nexusohm.com/products/xps-16-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Platinum",
        "hex": "#C9CBD0"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "thinkpad-x1-carbon",
    "sku": "LEN-X1C14-26",
    "brand": "LENOVO",
    "title": "ThinkPad X1 Carbon Gen 14",
    "category": "computing",
    "priceMinor": 199900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 18,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Business ultralight, from 0.977 kg",
      "2.8K 120Hz OLED option",
      "Intel Core Ultra Series 3"
    ],
    "specs": [
      {
        "label": "Processor",
        "value": "Intel Core Ultra Series 3, up to Core Ultra X7 368H"
      },
      {
        "label": "Graphics",
        "value": "Intel Graphics or Intel Arc B390"
      },
      {
        "label": "Display",
        "value": "14in WUXGA IPS, 500 nits; or 2.8K (2880×1800) OLED, 120Hz, DisplayHDR True Black 500"
      },
      {
        "label": "Memory",
        "value": "16GB to 64GB LPDDR5X, soldered"
      },
      {
        "label": "Storage",
        "value": "Up to 2TB PCIe SSD"
      },
      {
        "label": "Ports",
        "value": "3× Thunderbolt 4, USB-A 5Gbps, HDMI, 3.5mm combo jack"
      },
      {
        "label": "Battery",
        "value": "58Wh, up to 19.2 hours (MobileMark 30)"
      },
      {
        "label": "Wireless",
        "value": "Wi-Fi 7, Bluetooth 5.4"
      },
      {
        "label": "Weight",
        "value": "From 0.977 kg (2.15 lb)"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/thinkpad-x1-carbon-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/thinkpad-x1-carbon-2.webp",
      "thumb": "https://media.nexusohm.com/products/thinkpad-x1-carbon-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-1.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-2.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-3.webp",
        "https://media.nexusohm.com/products/thinkpad-x1-carbon-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "zenbook-s14",
    "sku": "ASU-ZS14-26",
    "brand": "ASUS",
    "title": "Zenbook S14 (2026)",
    "category": "computing",
    "priceMinor": 189900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "50 TOPS NPU",
      "14\" 3K 120Hz OLED",
      "77Wh, up to 27h"
    ],
    "specs": [
      {
        "label": "Processor",
        "value": "Intel Core Ultra 9 386H, 16 cores"
      },
      {
        "label": "NPU",
        "value": "Up to 50 TOPS, Copilot+ PC"
      },
      {
        "label": "Display",
        "value": "14in 3K Lumina OLED, 120Hz, 1,100 nits"
      },
      {
        "label": "Memory",
        "value": "32GB RAM"
      },
      {
        "label": "Storage",
        "value": "1TB SSD"
      },
      {
        "label": "Battery",
        "value": "77Wh, up to 27 hours"
      },
      {
        "label": "Thickness and weight",
        "value": "1.1 cm, 1.2 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/zenbook-s14-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/zenbook-s14-2.webp",
      "thumb": "https://media.nexusohm.com/products/zenbook-s14-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/zenbook-s14-1.webp",
        "https://media.nexusohm.com/products/zenbook-s14-2.webp",
        "https://media.nexusohm.com/products/zenbook-s14-3.webp",
        "https://media.nexusohm.com/products/zenbook-s14-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Scandinavian White",
        "hex": "#E9E6DF"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "zenbook-duo",
    "sku": "ASU-ZDUO-26",
    "brand": "ASUS",
    "title": "Zenbook Duo (2026)",
    "category": "computing",
    "priceMinor": 249999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "badge": "LIMITED_EDITION",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Two 14\" 3K 144Hz OLEDs",
      "Up to Core Ultra X9 388H",
      "99Wh battery"
    ],
    "specs": [
      {
        "label": "Processor",
        "value": "Up to Intel Core Ultra X9 388H, 16 cores, up to 5.1GHz"
      },
      {
        "label": "NPU",
        "value": "Up to 50 TOPS"
      },
      {
        "label": "Displays",
        "value": "Two 14in 3K (2880×1800) Lumina Pro OLED touchscreens, 144Hz, 500 nits (1,000 HDR)"
      },
      {
        "label": "Keyboard",
        "value": "Detachable, magnetic"
      },
      {
        "label": "Stand",
        "value": "Built-in kickstand"
      },
      {
        "label": "Battery",
        "value": "99Wh"
      },
      {
        "label": "Ports",
        "value": "2× Thunderbolt 4, USB-A 10Gbps, HDMI 2.1"
      },
      {
        "label": "Wireless",
        "value": "Wi-Fi 7, Bluetooth 5.4"
      },
      {
        "label": "Chassis",
        "value": "Ceraluminum"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/zenbook-duo-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/zenbook-duo-2.webp",
      "thumb": "https://media.nexusohm.com/products/zenbook-duo-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/zenbook-duo-1.webp",
        "https://media.nexusohm.com/products/zenbook-duo-2.webp",
        "https://media.nexusohm.com/products/zenbook-duo-3.webp",
        "https://media.nexusohm.com/products/zenbook-duo-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Inkwell Grey",
        "hex": "#40434A"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "airpods-max",
    "sku": "APL-APM2-101",
    "brand": "APPLE",
    "title": "AirPods Max 2",
    "category": "audio",
    "priceMinor": 54900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 34,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "H2 chip in each ear cup",
      "Lossless audio over USB-C",
      "20 hours with ANC"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Apple H2 headphone chip in each ear cup"
      },
      {
        "label": "Driver",
        "value": "Apple-designed dynamic driver"
      },
      {
        "label": "Noise control",
        "value": "Active Noise Cancellation, Transparency, Conversation Awareness, Voice Isolation, Loud Sound Reduction"
      },
      {
        "label": "Audio",
        "value": "Personalized Spatial Audio with dynamic head tracking, Adaptive Audio, Adaptive EQ"
      },
      {
        "label": "Wired audio",
        "value": "Lossless and ultra-low-latency audio over USB-C"
      },
      {
        "label": "Battery",
        "value": "Up to 20 hours with ANC; 5 min charge for about 1.5 hours"
      },
      {
        "label": "Weight",
        "value": "386.2 g"
      },
      {
        "label": "In the box",
        "value": "Smart Case, USB-C charge cable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/airpods-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/airpods-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/airpods-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/airpods-max-1.webp",
        "https://media.nexusohm.com/products/airpods-max-2.webp",
        "https://media.nexusohm.com/products/airpods-max-3.webp",
        "https://media.nexusohm.com/products/airpods-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "macbook-pro",
    "sku": "APL-MBP16-102",
    "brand": "APPLE",
    "title": "MacBook Pro 16\" M5 Pro",
    "category": "computing",
    "priceMinor": 249900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "M5 Pro, 18-core CPU",
      "16.2\" Liquid Retina XDR",
      "Up to 24h battery"
    ],
    "specs": [
      {
        "label": "Chip",
        "value": "Apple M5 Pro, 18-core CPU (6 super + 12 performance), 20-core GPU"
      },
      {
        "label": "Memory",
        "value": "24GB unified, up to 128GB with M5 Max"
      },
      {
        "label": "Storage",
        "value": "1TB SSD, configurable to 2TB or 4TB"
      },
      {
        "label": "Display",
        "value": "16.2in Liquid Retina XDR, 3456×2234, up to 120Hz"
      },
      {
        "label": "Brightness",
        "value": "1,000 nits sustained full screen"
      },
      {
        "label": "Battery",
        "value": "Up to 24 hours video streaming"
      },
      {
        "label": "Ports",
        "value": "3× Thunderbolt 5, HDMI, SDXC, MagSafe 3"
      },
      {
        "label": "Weight",
        "value": "2.14 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/macbook-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/macbook-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/macbook-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/macbook-pro-1.webp",
        "https://media.nexusohm.com/products/macbook-pro-2.webp",
        "https://media.nexusohm.com/products/macbook-pro-3.webp",
        "https://media.nexusohm.com/products/macbook-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "watch-ultra",
    "sku": "APL-AWU4-103",
    "brand": "APPLE",
    "title": "Apple Watch Ultra 4",
    "category": "computing",
    "priceMinor": 79900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 7,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "49mm Grade 5 titanium",
      "Up to 50h battery",
      "100m water, 40m dive"
    ],
    "specs": [
      {
        "label": "Case",
        "value": "49mm Grade 5 titanium"
      },
      {
        "label": "Display",
        "value": "Always-On Retina, wide-angle OLED, LTPO3, 3,000 nits"
      },
      {
        "label": "Chip",
        "value": "S11 SiP, 4-core Neural Engine, 64GB"
      },
      {
        "label": "Battery",
        "value": "Up to 50 hours, 84 hours in Low Power Mode"
      },
      {
        "label": "Water",
        "value": "100m; recreational scuba diving to 40m"
      },
      {
        "label": "GPS",
        "value": "Precision dual-frequency (GPS, Galileo, QZSS, BeiDou)"
      },
      {
        "label": "Sensors",
        "value": "Electrical and optical heart, blood oxygen, temperature, depth gauge, water temperature"
      },
      {
        "label": "Connectivity",
        "value": "5G and LTE (cellular model), Wi-Fi 4, Bluetooth 5.3, second-generation Ultra Wideband"
      },
      {
        "label": "Durability",
        "value": "MIL-STD 810H, IP6X dust"
      },
      {
        "label": "Weight",
        "value": "63.0 g (Natural)"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/watch-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/watch-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/watch-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/watch-ultra-1.webp",
        "https://media.nexusohm.com/products/watch-ultra-2.webp",
        "https://media.nexusohm.com/products/watch-ultra-3.webp",
        "https://media.nexusohm.com/products/watch-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "galaxy-s26",
    "sku": "SAM-S26-104",
    "brand": "SAMSUNG",
    "title": "Galaxy S26",
    "category": "phones",
    "priceMinor": 89999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 41,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "6.3\" 120Hz AMOLED",
      "50MP triple camera, 3× zoom",
      "4,300mAh battery"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.3in FHD+ Dynamic AMOLED 2X, 1–120Hz adaptive"
      },
      {
        "label": "Chip",
        "value": "Exynos 2600 in Malaysia; Snapdragon 8 Elite Gen 5 for Galaxy in some markets"
      },
      {
        "label": "Memory",
        "value": "12GB RAM with 256GB or 512GB"
      },
      {
        "label": "Rear cameras",
        "value": "50MP wide f/1.8, 12MP ultrawide f/2.2, 10MP 3× telephoto f/2.4"
      },
      {
        "label": "Zoom",
        "value": "Up to 30× Space Zoom"
      },
      {
        "label": "Front camera",
        "value": "12MP f/2.2"
      },
      {
        "label": "Battery",
        "value": "4,300mAh"
      },
      {
        "label": "Charging",
        "value": "25W wired (up to 55% in about 30 min), 15W wireless"
      },
      {
        "label": "Durability",
        "value": "IP68"
      },
      {
        "label": "Size and weight",
        "value": "149.6 × 71.5 × 7.2 mm, 167 g"
      },
      {
        "label": "Software",
        "value": "Android 16, One UI 8.5"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-s26-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-s26-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-s26-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-s26-1.webp",
        "https://media.nexusohm.com/products/galaxy-s26-2.webp",
        "https://media.nexusohm.com/products/galaxy-s26-3.webp",
        "https://media.nexusohm.com/products/galaxy-s26-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "galaxy-buds",
    "sku": "SAM-BUD4-105",
    "brand": "SAMSUNG",
    "title": "Galaxy Buds4 Pro",
    "category": "audio",
    "priceMinor": 24900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 63,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Adaptive ANC 2.0",
      "24-bit/96kHz Hi-Fi audio",
      "IP57 rated"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "2-way woofer and tweeter, each with its own amplifier"
      },
      {
        "label": "Noise control",
        "value": "Adaptive ANC 2.0"
      },
      {
        "label": "Hi-Fi audio",
        "value": "24-bit/96kHz with SSC UHQ on eligible Galaxy devices; LC3 over LE Audio"
      },
      {
        "label": "Battery",
        "value": "About 6 hours with ANC, 30 hours with case"
      },
      {
        "label": "Water resistance",
        "value": "IP57"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/galaxy-buds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/galaxy-buds-2.webp",
      "thumb": "https://media.nexusohm.com/products/galaxy-buds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/galaxy-buds-1.webp",
        "https://media.nexusohm.com/products/galaxy-buds-2.webp",
        "https://media.nexusohm.com/products/galaxy-buds-3.webp",
        "https://media.nexusohm.com/products/galaxy-buds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "odyssey-oled",
    "sku": "SAM-G95-106",
    "brand": "SAMSUNG",
    "title": "Odyssey OLED G9 49\"",
    "category": "peripherals",
    "priceMinor": 159900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 5,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "5120 × 1440 OLED",
      "240Hz, 0.03ms",
      "Dual QHD ultrawide"
    ],
    "specs": [
      {
        "label": "Panel",
        "value": "49in QD-OLED, 1800R curve"
      },
      {
        "label": "Resolution",
        "value": "5120 × 1440 (Dual QHD)"
      },
      {
        "label": "Refresh",
        "value": "240Hz, 0.03ms GtG"
      },
      {
        "label": "HDR",
        "value": "VESA DisplayHDR True Black 400"
      },
      {
        "label": "Colour",
        "value": "99% DCI-P3"
      },
      {
        "label": "Ports",
        "value": "DisplayPort 1.4, 2× HDMI 2.1, USB hub"
      },
      {
        "label": "Sync",
        "value": "AMD FreeSync Premium Pro"
      },
      {
        "label": "Stand",
        "value": "Height, tilt and swivel adjustable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/odyssey-oled-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/odyssey-oled-2.webp",
      "thumb": "https://media.nexusohm.com/products/odyssey-oled-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/odyssey-oled-1.webp",
        "https://media.nexusohm.com/products/odyssey-oled-2.webp",
        "https://media.nexusohm.com/products/odyssey-oled-3.webp",
        "https://media.nexusohm.com/products/odyssey-oled-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "wh1000xm6",
    "sku": "SNY-XM6-107",
    "brand": "SONY",
    "title": "WH-1000XM6 Wireless",
    "category": "audio",
    "priceMinor": 44900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 48,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "QN3 processor, 12 mics",
      "30-hour battery with NC",
      "LDAC Hi-Res audio"
    ],
    "specs": [
      {
        "label": "Processor",
        "value": "HD Noise Cancelling Processor QN3"
      },
      {
        "label": "Microphones",
        "value": "12"
      },
      {
        "label": "Driver",
        "value": "Carbon fibre composite dome"
      },
      {
        "label": "Battery",
        "value": "Up to 30 hours with NC, 40 with NC off"
      },
      {
        "label": "Charging time",
        "value": "About 3.5 hours"
      },
      {
        "label": "Codec",
        "value": "LDAC, AAC, SBC, LC3"
      },
      {
        "label": "Frequency",
        "value": "4Hz – 40,000Hz (wired)"
      },
      {
        "label": "Bluetooth",
        "value": "5.3, multipoint with 2 devices"
      },
      {
        "label": "Weight",
        "value": "254 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/wh1000xm6-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/wh1000xm6-2.webp",
      "thumb": "https://media.nexusohm.com/products/wh1000xm6-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/wh1000xm6-1.webp",
        "https://media.nexusohm.com/products/wh1000xm6-2.webp",
        "https://media.nexusohm.com/products/wh1000xm6-3.webp",
        "https://media.nexusohm.com/products/wh1000xm6-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "alpha-7cr",
    "sku": "SNY-A7CR-108",
    "brand": "SONY",
    "title": "Alpha 7CR Full-Frame",
    "category": "imaging",
    "priceMinor": 289900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 8,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "61MP full-frame camera",
      "7-stop in-body stabilisation",
      "AI subject-tracking autofocus"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "61MP full-frame back-illuminated CMOS"
      },
      {
        "label": "Stabilisation",
        "value": "5-axis in-body, 7.0 stops (CIPA)"
      },
      {
        "label": "Autofocus",
        "value": "693 phase-detect points, AI subject recognition"
      },
      {
        "label": "ISO",
        "value": "100–32,000, expandable 50–102,400"
      },
      {
        "label": "Video",
        "value": "4K, oversampled from 6K"
      },
      {
        "label": "Viewfinder",
        "value": "2.36M-dot OLED, 0.70×"
      },
      {
        "label": "Weight",
        "value": "515 g with battery and card, 430 g body only"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/alpha-7cr-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/alpha-7cr-2.webp",
      "thumb": "https://media.nexusohm.com/products/alpha-7cr-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/alpha-7cr-1.webp",
        "https://media.nexusohm.com/products/alpha-7cr-2.webp",
        "https://media.nexusohm.com/products/alpha-7cr-3.webp",
        "https://media.nexusohm.com/products/alpha-7cr-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "fx3-cinema",
    "sku": "SNY-FX3-109",
    "brand": "SONY",
    "title": "FX3 Cinema Line",
    "category": "imaging",
    "priceMinor": 389900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 3,
    "badge": "LIMITED_EDITION",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Full-frame cinema camera",
      "4K 120p video",
      "15+ stops dynamic range"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "Full-frame back-illuminated CMOS, 12.1MP stills"
      },
      {
        "label": "Video",
        "value": "4K up to 120p"
      },
      {
        "label": "Dynamic range",
        "value": "15+ stops, S-Cinetone and S-Log3"
      },
      {
        "label": "ISO",
        "value": "80–102,400 for movies, expandable to 409,600"
      },
      {
        "label": "Audio",
        "value": "XLR handle: 2 × XLR/TRS inputs plus 3.5mm"
      },
      {
        "label": "Mount",
        "value": "Sony E-mount"
      },
      {
        "label": "Size and weight",
        "value": "129.7 × 77.8 × 84.5 mm, 715 g with battery and card"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/fx3-cinema-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/fx3-cinema-2.webp",
      "thumb": "https://media.nexusohm.com/products/fx3-cinema-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/fx3-cinema-1.webp",
        "https://media.nexusohm.com/products/fx3-cinema-2.webp",
        "https://media.nexusohm.com/products/fx3-cinema-3.webp",
        "https://media.nexusohm.com/products/fx3-cinema-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "qc-ultra",
    "sku": "BSE-QCU-110",
    "brand": "BOSE",
    "title": "QuietComfort Ultra Headphones (2nd Gen)",
    "category": "audio",
    "priceMinor": 44900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 27,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "30-hour battery with ANC",
      "Lossless USB-C audio",
      "CustomTune, Cinema Mode"
    ],
    "specs": [
      {
        "label": "Noise control",
        "value": "CustomTune noise cancelling"
      },
      {
        "label": "Audio",
        "value": "Immersive Audio with Cinema Mode"
      },
      {
        "label": "Battery",
        "value": "Up to 30 hours with ANC, 23 with Immersive Audio, 45 with ANC off"
      },
      {
        "label": "Wired audio",
        "value": "Lossless over USB-C (16-bit, 44.1/48kHz)"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, AAC, SBC"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/qc-ultra-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/qc-ultra-2.webp",
      "thumb": "https://media.nexusohm.com/products/qc-ultra-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/qc-ultra-1.webp",
        "https://media.nexusohm.com/products/qc-ultra-2.webp",
        "https://media.nexusohm.com/products/qc-ultra-3.webp",
        "https://media.nexusohm.com/products/qc-ultra-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "open-earbuds",
    "sku": "BSE-UOE-111",
    "brand": "BOSE",
    "title": "Ultra Open Earbuds",
    "category": "audio",
    "priceMinor": 29900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Open-ear: hear what's around you",
      "Up to 7h, 19.5h more in case",
      "IPX4 sweat resistant"
    ],
    "specs": [
      {
        "label": "Design",
        "value": "Open-ear cuff, nothing in the ear canal"
      },
      {
        "label": "Battery",
        "value": "Up to 7 hours, 4 hours with Immersive Audio"
      },
      {
        "label": "Case",
        "value": "Up to 19.5 extra hours"
      },
      {
        "label": "Water resistance",
        "value": "IPX4"
      },
      {
        "label": "Codec",
        "value": "AAC, SBC"
      },
      {
        "label": "Controls",
        "value": "Buttons, customisable in the Bose app"
      },
      {
        "label": "Weight",
        "value": "About 6.4 g (0.014 lb) per earbud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/open-earbuds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/open-earbuds-2.webp",
      "thumb": "https://media.nexusohm.com/products/open-earbuds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/open-earbuds-1.webp",
        "https://media.nexusohm.com/products/open-earbuds-2.webp",
        "https://media.nexusohm.com/products/open-earbuds-3.webp",
        "https://media.nexusohm.com/products/open-earbuds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "soundlink-max",
    "sku": "BSE-SLM-112",
    "brand": "BOSE",
    "title": "SoundLink Max Portable",
    "category": "audio",
    "priceMinor": 39900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 19,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "20-hour battery",
      "IP67 rated",
      "aptX Adaptive"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "3 transducers, 2 passive radiators"
      },
      {
        "label": "Battery",
        "value": "Up to 20 hours"
      },
      {
        "label": "Durability",
        "value": "IP67 water and dust resistant"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive (Snapdragon Sound), AAC, SBC"
      },
      {
        "label": "Connectivity",
        "value": "Bluetooth 5.3, 3.5mm aux in"
      },
      {
        "label": "Power out",
        "value": "USB-C charges a phone"
      },
      {
        "label": "Handle",
        "value": "Removable rope handle"
      },
      {
        "label": "Size and weight",
        "value": "265 × 120 × 105 mm, just under 5 lb"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/soundlink-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/soundlink-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/soundlink-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/soundlink-max-1.webp",
        "https://media.nexusohm.com/products/soundlink-max-2.webp",
        "https://media.nexusohm.com/products/soundlink-max-3.webp",
        "https://media.nexusohm.com/products/soundlink-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Pacific Blue",
        "hex": "#2C4A6E"
      }
    ]
  },
  {
    "id": "hd900s",
    "sku": "SEN-HD800S-113",
    "brand": "SENNHEISER",
    "title": "HD 800 S",
    "category": "audio",
    "priceMinor": 199995,
    "currency": "USD",
    "inStock": true,
    "stockCount": 14,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "56mm ring radiator drivers",
      "4Hz – 51kHz response",
      "Open-back, 300 Ω"
    ],
    "specs": [
      {
        "label": "Transducer",
        "value": "56mm ring radiator dynamic"
      },
      {
        "label": "Design",
        "value": "Open-back, circumaural"
      },
      {
        "label": "Frequency response",
        "value": "4Hz – 51,000Hz"
      },
      {
        "label": "Impedance",
        "value": "300 Ω"
      },
      {
        "label": "Sound pressure level",
        "value": "102 dB (1 V)"
      },
      {
        "label": "THD",
        "value": "Under 0.02% (1 kHz, 1 Vrms)"
      },
      {
        "label": "Cables",
        "value": "3m with 6.35mm plug, 3m with 4.4mm balanced plug"
      },
      {
        "label": "Weight",
        "value": "330 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/hd900s-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/hd900s-2.webp",
      "thumb": "https://media.nexusohm.com/products/hd900s-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/hd900s-1.webp",
        "https://media.nexusohm.com/products/hd900s-2.webp",
        "https://media.nexusohm.com/products/hd900s-3.webp",
        "https://media.nexusohm.com/products/hd900s-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Titanium",
        "hex": "#9A9AA0"
      }
    ]
  },
  {
    "id": "momentum-4",
    "sku": "SEN-MOM4-114",
    "brand": "SENNHEISER",
    "title": "Momentum 4 Wireless",
    "category": "audio",
    "priceMinor": 29995,
    "currency": "USD",
    "inStock": true,
    "stockCount": 22,
    "badge": "DISCOUNT",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "60-hour battery",
      "Hybrid adaptive ANC",
      "aptX Adaptive"
    ],
    "specs": [
      {
        "label": "Driver",
        "value": "42mm dynamic"
      },
      {
        "label": "Battery",
        "value": "Up to 60 hours with ANC; 5 min charge for up to 4 hours"
      },
      {
        "label": "Noise control",
        "value": "Hybrid adaptive ANC"
      },
      {
        "label": "Codec",
        "value": "aptX Adaptive, aptX, AAC, SBC"
      },
      {
        "label": "Frequency",
        "value": "6Hz – 22kHz"
      },
      {
        "label": "Microphones",
        "value": "4, beamforming (2 per side)"
      },
      {
        "label": "Bluetooth",
        "value": "5.2"
      },
      {
        "label": "In the box",
        "value": "Carry case, USB-C cable, audio cable"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/momentum-4-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/momentum-4-2.webp",
      "thumb": "https://media.nexusohm.com/products/momentum-4-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/momentum-4-1.webp",
        "https://media.nexusohm.com/products/momentum-4-2.webp",
        "https://media.nexusohm.com/products/momentum-4-3.webp",
        "https://media.nexusohm.com/products/momentum-4-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "mavic-4-pro",
    "sku": "DJI-MV4-115",
    "brand": "DJI",
    "title": "Mavic 4 Pro",
    "category": "imaging",
    "priceMinor": 269900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 17,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "100MP 4/3 Hasselblad camera",
      "6K/60fps video",
      "51-minute flight"
    ],
    "specs": [
      {
        "label": "Cameras",
        "value": "100MP 4/3 Hasselblad, 48MP 1/1.3in medium tele, 50MP 1/1.5in tele"
      },
      {
        "label": "Video",
        "value": "6K up to 60fps, 4K up to 120fps"
      },
      {
        "label": "Flight time",
        "value": "Up to 51 minutes"
      },
      {
        "label": "Transmission",
        "value": "O4+, up to 30 km (FCC), 15 km (CE)"
      },
      {
        "label": "Obstacle sensing",
        "value": "Omnidirectional vision, forward LiDAR, downward infrared"
      },
      {
        "label": "Storage",
        "value": "64GB internal (512GB in the Creator Combo)"
      },
      {
        "label": "Weight",
        "value": "About 1,063 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mavic-4-pro-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mavic-4-pro-2.webp",
      "thumb": "https://media.nexusohm.com/products/mavic-4-pro-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mavic-4-pro-1.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-2.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-3.webp",
        "https://media.nexusohm.com/products/mavic-4-pro-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "osmo-pocket",
    "sku": "DJI-OP4-116",
    "brand": "DJI",
    "title": "Osmo Pocket 4",
    "category": "imaging",
    "priceMinor": 79900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 31,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "1-inch CMOS sensor",
      "4K/60fps, 4K/240fps slow-mo",
      "107GB built-in storage"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "1in CMOS"
      },
      {
        "label": "Lens",
        "value": "20mm equivalent, f/2.0"
      },
      {
        "label": "Video",
        "value": "4K up to 60fps; slow motion up to 4K/240fps"
      },
      {
        "label": "Gimbal",
        "value": "3-axis mechanical"
      },
      {
        "label": "Screen",
        "value": "2.0in, 556×314, 1,000 nits"
      },
      {
        "label": "Storage",
        "value": "107GB built in"
      },
      {
        "label": "Battery",
        "value": "240 min at 1080p/24fps; 80% in 18 min"
      },
      {
        "label": "Audio",
        "value": "3 microphones"
      },
      {
        "label": "Size and weight",
        "value": "144.2 × 44.4 × 33.5 mm, 190.5 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/osmo-pocket-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/osmo-pocket-2.webp",
      "thumb": "https://media.nexusohm.com/products/osmo-pocket-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/osmo-pocket-1.webp",
        "https://media.nexusohm.com/products/osmo-pocket-2.webp",
        "https://media.nexusohm.com/products/osmo-pocket-3.webp",
        "https://media.nexusohm.com/products/osmo-pocket-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "rs4-gimbal",
    "sku": "DJI-RS4-117",
    "brand": "DJI",
    "title": "RS 4 Pro Gimbal",
    "category": "imaging",
    "priceMinor": 86900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 9,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "4.5kg payload",
      "LiDAR autofocus with Focus Pro",
      "Up to 29h with BG70 grip"
    ],
    "specs": [
      {
        "label": "Payload",
        "value": "4.5 kg"
      },
      {
        "label": "Battery",
        "value": "13 hours (BG30 grip), up to 29 hours with the BG70 grip"
      },
      {
        "label": "Charging",
        "value": "About 1.5 hours"
      },
      {
        "label": "Axes",
        "value": "3-axis with automatic locks"
      },
      {
        "label": "Screen",
        "value": "OLED touchscreen"
      },
      {
        "label": "Focus",
        "value": "Autofocus for manual lenses with DJI Focus Pro LiDAR"
      },
      {
        "label": "Weight",
        "value": "Gimbal 1,242 g, grip 265 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/rs4-gimbal-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/rs4-gimbal-2.webp",
      "thumb": "https://media.nexusohm.com/products/rs4-gimbal-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/rs4-gimbal-1.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-2.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-3.webp",
        "https://media.nexusohm.com/products/rs4-gimbal-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "mx-master",
    "sku": "LOG-MXM4-118",
    "brand": "LOGITECH",
    "title": "MX Master 4",
    "category": "peripherals",
    "priceMinor": 11900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 87,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Haptic Sense Panel",
      "8,000 DPI, tracks on glass",
      "70-day battery"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "Darkfield, 200–8,000 DPI, tracks on glass"
      },
      {
        "label": "Haptics",
        "value": "Haptic Sense Panel with Actions Ring"
      },
      {
        "label": "Scrolling",
        "value": "MagSpeed, up to 1,000 lines per second"
      },
      {
        "label": "Buttons",
        "value": "8"
      },
      {
        "label": "Battery",
        "value": "70 days; 1 min charge for 3 hours"
      },
      {
        "label": "Connectivity",
        "value": "Logi Bolt receiver, Bluetooth Low Energy"
      },
      {
        "label": "Weight",
        "value": "150 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mx-master-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mx-master-2.webp",
      "thumb": "https://media.nexusohm.com/products/mx-master-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mx-master-1.webp",
        "https://media.nexusohm.com/products/mx-master-2.webp",
        "https://media.nexusohm.com/products/mx-master-3.webp",
        "https://media.nexusohm.com/products/mx-master-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "mx-mechanical",
    "sku": "LOG-MXK-119",
    "brand": "LOGITECH",
    "title": "MX Mechanical Keyboard",
    "category": "peripherals",
    "priceMinor": 16900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 44,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Low-profile mechanical",
      "Smart backlighting",
      "15 days lit, 10 months unlit"
    ],
    "specs": [
      {
        "label": "Switches",
        "value": "Low-profile tactile, clicky or linear"
      },
      {
        "label": "Key travel",
        "value": "1.3 mm actuation, 3.2 mm total"
      },
      {
        "label": "Layout",
        "value": "Full size with numeric keypad"
      },
      {
        "label": "Backlight",
        "value": "Smart illumination"
      },
      {
        "label": "Battery",
        "value": "15 days with backlight, 10 months without; 4 h full charge"
      },
      {
        "label": "Connectivity",
        "value": "Logi Bolt, Bluetooth 5.2, up to 3 devices"
      },
      {
        "label": "Compatibility",
        "value": "Windows, macOS, Linux, ChromeOS, iPadOS, Android"
      },
      {
        "label": "Build",
        "value": "Low-carbon aluminium and plastic"
      },
      {
        "label": "Weight",
        "value": "828 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/mx-mechanical-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/mx-mechanical-2.webp",
      "thumb": "https://media.nexusohm.com/products/mx-mechanical-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/mx-mechanical-1.webp",
        "https://media.nexusohm.com/products/mx-mechanical-2.webp",
        "https://media.nexusohm.com/products/mx-mechanical-3.webp",
        "https://media.nexusohm.com/products/mx-mechanical-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      }
    ]
  },
  {
    "id": "brio-webcam",
    "sku": "LOG-BRIO-120",
    "brand": "LOGITECH",
    "title": "Brio 4K Webcam",
    "category": "imaging",
    "priceMinor": 19900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 52,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "4K at 30fps with HDR",
      "Windows Hello IR sign-in",
      "65°, 78° or 90° view"
    ],
    "specs": [
      {
        "label": "Resolution",
        "value": "4K at 30fps, 1080p at 60fps, 720p at 90fps"
      },
      {
        "label": "Field of view",
        "value": "65°, 78° or 90°"
      },
      {
        "label": "HDR",
        "value": "RightLight 3 with HDR"
      },
      {
        "label": "Zoom",
        "value": "5× digital"
      },
      {
        "label": "Security",
        "value": "Windows Hello IR face recognition"
      },
      {
        "label": "Privacy",
        "value": "Flip-down privacy shutter"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/brio-webcam-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/brio-webcam-2.webp",
      "thumb": "https://media.nexusohm.com/products/brio-webcam-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/brio-webcam-1.webp",
        "https://media.nexusohm.com/products/brio-webcam-2.webp",
        "https://media.nexusohm.com/products/brio-webcam-3.webp",
        "https://media.nexusohm.com/products/brio-webcam-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "blackwidow",
    "sku": "RZR-BW4-121",
    "brand": "RAZER",
    "title": "BlackWidow V4 Pro",
    "category": "peripherals",
    "priceMinor": 22900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 23,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "8000Hz polling",
      "Command Dial, 8 macro keys",
      "Magnetic wrist rest"
    ],
    "specs": [
      {
        "label": "Switches",
        "value": "Razer Green (clicky) or Yellow (linear), up to 100 million keystrokes"
      },
      {
        "label": "Polling",
        "value": "Up to 8,000Hz"
      },
      {
        "label": "Controls",
        "value": "Razer Command Dial, media roller with 4 media keys"
      },
      {
        "label": "Macros",
        "value": "8 dedicated macro keys (5 on the left, 3 on the side)"
      },
      {
        "label": "Lighting",
        "value": "Per-key Chroma RGB, 38-zone underglow"
      },
      {
        "label": "Wrist rest",
        "value": "Magnetic plush leatherette"
      },
      {
        "label": "Build",
        "value": "5052 aluminium alloy top case"
      },
      {
        "label": "Keycaps",
        "value": "Doubleshot ABS"
      },
      {
        "label": "Connection",
        "value": "Wired, detachable USB-C, USB 2.0 passthrough"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/blackwidow-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/blackwidow-2.webp",
      "thumb": "https://media.nexusohm.com/products/blackwidow-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/blackwidow-1.webp",
        "https://media.nexusohm.com/products/blackwidow-2.webp",
        "https://media.nexusohm.com/products/blackwidow-3.webp",
        "https://media.nexusohm.com/products/blackwidow-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "viper-v3",
    "sku": "RZR-VV3-122",
    "brand": "RAZER",
    "title": "Viper V3 Pro",
    "category": "peripherals",
    "priceMinor": 15900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 4,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Focus Pro 35K Gen-2 sensor",
      "54 g",
      "8000Hz HyperPolling"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "Focus Pro 35K Optical Gen-2, 99.8% resolution accuracy"
      },
      {
        "label": "DPI",
        "value": "Up to 35,000"
      },
      {
        "label": "Polling",
        "value": "Up to 8,000Hz with the HyperPolling dongle"
      },
      {
        "label": "Switches",
        "value": "Optical Gen-3"
      },
      {
        "label": "Battery",
        "value": "Up to 95 hours at 1000Hz"
      },
      {
        "label": "Shape",
        "value": "Symmetrical, buttons for the right hand"
      },
      {
        "label": "Weight",
        "value": "54 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/viper-v3-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/viper-v3-2.webp",
      "thumb": "https://media.nexusohm.com/products/viper-v3-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/viper-v3-1.webp",
        "https://media.nexusohm.com/products/viper-v3-2.webp",
        "https://media.nexusohm.com/products/viper-v3-3.webp",
        "https://media.nexusohm.com/products/viper-v3-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "blade-16",
    "sku": "RZR-BL16-123",
    "brand": "RAZER",
    "title": "Blade 16 (2026)",
    "category": "computing",
    "priceMinor": 329900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Up to RTX 5090 Laptop GPU",
      "16\" QHD+ 240Hz OLED",
      "Intel Core Ultra 9 386H"
    ],
    "specs": [
      {
        "label": "CPU",
        "value": "Intel Core Ultra 9 386H, 16 cores, up to 4.9GHz"
      },
      {
        "label": "GPU",
        "value": "Up to NVIDIA GeForce RTX 5090 Laptop, up to 165 watts TGP"
      },
      {
        "label": "Display",
        "value": "16in QHD+ OLED, up to 240Hz, DisplayHDR True Black 1000, up to 1,100 nits"
      },
      {
        "label": "Memory",
        "value": "Up to 64GB LPDDR5-9600"
      },
      {
        "label": "Thickness and weight",
        "value": "14.9 mm, about 2.14 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/blade-16-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/blade-16-2.webp",
      "thumb": "https://media.nexusohm.com/products/blade-16-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/blade-16-1.webp",
        "https://media.nexusohm.com/products/blade-16-2.webp",
        "https://media.nexusohm.com/products/blade-16-3.webp",
        "https://media.nexusohm.com/products/blade-16-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "prime-powerbank",
    "sku": "ANK-P26-124",
    "brand": "ANKER",
    "title": "Prime Power Bank (26K, 300W)",
    "category": "computing",
    "priceMinor": 22999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 96,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "300W total output",
      "26,250mAh, 99.75Wh",
      "250W fast recharge"
    ],
    "specs": [
      {
        "label": "Capacity",
        "value": "26,250mAh (99.75Wh)"
      },
      {
        "label": "Output",
        "value": "300W total"
      },
      {
        "label": "Ports",
        "value": "2× USB-C up to 140W each, 1× USB-A up to 22.5W"
      },
      {
        "label": "Recharge",
        "value": "250W over both USB-C ports; 50% in 13 min, 80% in 40 min"
      },
      {
        "label": "Display",
        "value": "Smart display, app control over Bluetooth"
      },
      {
        "label": "Safety",
        "value": "ActiveShield 4.0"
      },
      {
        "label": "Airline",
        "value": "Under the 100Wh carry-on limit"
      },
      {
        "label": "Size and weight",
        "value": "159.9 × 38 × 62.7 mm, 600 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/prime-powerbank-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/prime-powerbank-2.webp",
      "thumb": "https://media.nexusohm.com/products/prime-powerbank-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/prime-powerbank-1.webp",
        "https://media.nexusohm.com/products/prime-powerbank-2.webp",
        "https://media.nexusohm.com/products/prime-powerbank-3.webp",
        "https://media.nexusohm.com/products/prime-powerbank-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Graphite",
        "hex": "#3A3A3E"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "soundcore-liberty",
    "sku": "ANK-SCL5-125",
    "brand": "ANKER",
    "title": "Soundcore Liberty 5",
    "category": "audio",
    "priceMinor": 12999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 110,
    "badge": "DISCOUNT",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Adaptive ANC 3.0",
      "48 hours with case",
      "LDAC Hi-Res audio"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "9.2mm wool-paper diaphragm"
      },
      {
        "label": "Noise control",
        "value": "Adaptive ANC 3.0, adjusts every 0.3 s"
      },
      {
        "label": "Battery",
        "value": "12 hours buds, 48 with case; 8 and 32 with ANC"
      },
      {
        "label": "Quick charge",
        "value": "10 min for 5 hours"
      },
      {
        "label": "Codec",
        "value": "LDAC Hi-Res"
      },
      {
        "label": "Microphones",
        "value": "6, with AI wind reduction"
      },
      {
        "label": "Water resistance",
        "value": "IP55"
      },
      {
        "label": "Bluetooth",
        "value": "5.4"
      },
      {
        "label": "Charging",
        "value": "USB-C and wireless"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/soundcore-liberty-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/soundcore-liberty-2.webp",
      "thumb": "https://media.nexusohm.com/products/soundcore-liberty-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/soundcore-liberty-1.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-2.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-3.webp",
        "https://media.nexusohm.com/products/soundcore-liberty-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "gan-charger",
    "sku": "ANK-747-126",
    "brand": "ANKER",
    "title": "Prime Charger (250W, 6 Ports)",
    "category": "computing",
    "priceMinor": 14900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 71,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "250W across six ports",
      "140W from a single USB-C",
      "LCD with control dial"
    ],
    "specs": [
      {
        "label": "Output",
        "value": "250W total"
      },
      {
        "label": "Ports",
        "value": "4× USB-C, 2× USB-A"
      },
      {
        "label": "Fast charge",
        "value": "Up to 140W from USB-C 1"
      },
      {
        "label": "Display",
        "value": "2.26in LCD with smart control dial"
      },
      {
        "label": "Safety",
        "value": "ActiveShield 3.0"
      },
      {
        "label": "Technology",
        "value": "GaNPrime, PowerIQ 4.0"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/gan-charger-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/gan-charger-2.webp",
      "thumb": "https://media.nexusohm.com/products/gan-charger-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/gan-charger-1.webp",
        "https://media.nexusohm.com/products/gan-charger-2.webp",
        "https://media.nexusohm.com/products/gan-charger-3.webp",
        "https://media.nexusohm.com/products/gan-charger-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "phone-3a",
    "sku": "NTH-P3A-127",
    "brand": "NOTHING",
    "title": "Phone (3a) Pro",
    "category": "phones",
    "priceMinor": 47900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 38,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "50MP 3× periscope camera",
      "6.77\" 120Hz AMOLED",
      "5,000mAh, 50W charging"
    ],
    "specs": [
      {
        "label": "Display",
        "value": "6.77in AMOLED, 120Hz adaptive, 3,000 nits peak"
      },
      {
        "label": "Chip",
        "value": "Snapdragon 7s Gen 3"
      },
      {
        "label": "Memory",
        "value": "12GB RAM, 256GB storage"
      },
      {
        "label": "Rear cameras",
        "value": "50MP main, 50MP periscope (Sony LYTIA 600, OIS), 8MP ultrawide"
      },
      {
        "label": "Zoom",
        "value": "3× optical, 6× lossless, up to 60× ultra zoom"
      },
      {
        "label": "Battery",
        "value": "5,000mAh"
      },
      {
        "label": "Charging",
        "value": "50W wired"
      },
      {
        "label": "Glyph",
        "value": "Glyph Interface light strips"
      },
      {
        "label": "Durability",
        "value": "IP64"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/phone-3a-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/phone-3a-2.webp",
      "thumb": "https://media.nexusohm.com/products/phone-3a-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/phone-3a-1.webp",
        "https://media.nexusohm.com/products/phone-3a-2.webp",
        "https://media.nexusohm.com/products/phone-3a-3.webp",
        "https://media.nexusohm.com/products/phone-3a-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "ear-open",
    "sku": "NTH-EAR-128",
    "brand": "NOTHING",
    "title": "Ear (Open)",
    "category": "audio",
    "priceMinor": 14900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 6,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Open-ear: hear what's around you",
      "IP54 rated",
      "30 hours with case"
    ],
    "specs": [
      {
        "label": "Design",
        "value": "Open-ear, ear-hook fit"
      },
      {
        "label": "Driver",
        "value": "14.2mm dynamic"
      },
      {
        "label": "Battery",
        "value": "8 hours buds, 30 hours with case"
      },
      {
        "label": "Battery capacity",
        "value": "64mAh per bud, 635mAh case"
      },
      {
        "label": "Water resistance",
        "value": "IP54"
      },
      {
        "label": "Codec",
        "value": "AAC, SBC"
      },
      {
        "label": "Weight",
        "value": "8.1 g per bud"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/ear-open-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/ear-open-2.webp",
      "thumb": "https://media.nexusohm.com/products/ear-open-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/ear-open-1.webp",
        "https://media.nexusohm.com/products/ear-open-2.webp",
        "https://media.nexusohm.com/products/ear-open-3.webp",
        "https://media.nexusohm.com/products/ear-open-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "cmf-buds",
    "sku": "NTH-CMF-129",
    "brand": "NOTHING",
    "title": "CMF Buds Pro 2",
    "category": "audio",
    "priceMinor": 6900,
    "currency": "USD",
    "inStock": false,
    "stockCount": 0,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "50dB hybrid ANC",
      "11mm + 6mm dual drivers",
      "Up to 43h with case"
    ],
    "specs": [
      {
        "label": "Noise control",
        "value": "Hybrid ANC up to 50dB"
      },
      {
        "label": "Drivers",
        "value": "11mm + 6mm dual drivers"
      },
      {
        "label": "Microphones",
        "value": "6 HD mics"
      },
      {
        "label": "Codec",
        "value": "LDAC, AAC"
      },
      {
        "label": "Battery",
        "value": "Up to 43 hours with case (ANC off), 26 hours with ANC on"
      },
      {
        "label": "Case",
        "value": "Smart Dial controls"
      },
      {
        "label": "Water resistance",
        "value": "IP55"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/cmf-buds-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/cmf-buds-2.webp",
      "thumb": "https://media.nexusohm.com/products/cmf-buds-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/cmf-buds-1.webp",
        "https://media.nexusohm.com/products/cmf-buds-2.webp",
        "https://media.nexusohm.com/products/cmf-buds-3.webp",
        "https://media.nexusohm.com/products/cmf-buds-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Transparent",
        "hex": "#8E96A0"
      }
    ]
  },
  {
    "id": "q3-max",
    "sku": "KEY-Q3M-130",
    "brand": "KEYCHRON",
    "title": "Q3 Max QMK Custom",
    "category": "peripherals",
    "priceMinor": 22999,
    "currency": "USD",
    "inStock": true,
    "stockCount": 34,
    "badge": "NEW_DROP",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Double-gasket mount",
      "QMK / VIA",
      "Up to 180h battery"
    ],
    "specs": [
      {
        "label": "Layout",
        "value": "80% (tenkeyless)"
      },
      {
        "label": "Mount",
        "value": "Double gasket"
      },
      {
        "label": "Switches",
        "value": "Hot-swappable"
      },
      {
        "label": "Firmware",
        "value": "QMK and VIA"
      },
      {
        "label": "Connectivity",
        "value": "2.4GHz, Bluetooth 5.1 (3 devices), USB-C wired; 1000Hz"
      },
      {
        "label": "Battery",
        "value": "4000mAh, up to 180 hours"
      },
      {
        "label": "Case",
        "value": "CNC-machined 6063 aluminium"
      },
      {
        "label": "Keycaps",
        "value": "Double-shot PBT, OSA profile"
      },
      {
        "label": "Weight",
        "value": "2,045 g fully assembled"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/q3-max-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/q3-max-2.webp",
      "thumb": "https://media.nexusohm.com/products/q3-max-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/q3-max-1.webp",
        "https://media.nexusohm.com/products/q3-max-2.webp",
        "https://media.nexusohm.com/products/q3-max-3.webp",
        "https://media.nexusohm.com/products/q3-max-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "switch-set",
    "sku": "KEY-NBS-131",
    "brand": "KEYCHRON",
    "title": "Nebula Magnetic Switch Set ×110",
    "category": "peripherals",
    "priceMinor": 6900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 210,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Gateron double-rail magnetic",
      "0.2–3.8mm adjustable actuation",
      "For Keychron HE keyboards"
    ],
    "specs": [
      {
        "label": "Type",
        "value": "Gateron double-rail magnetic (Hall effect), linear"
      },
      {
        "label": "Actuation",
        "value": "Adjustable from 0.2 to 3.8 mm in 0.1 mm steps"
      },
      {
        "label": "Lubrication",
        "value": "Factory pre-lubed"
      },
      {
        "label": "Compatibility",
        "value": "Keychron Q HE and K HE, Lemokey P HE keyboards"
      },
      {
        "label": "Quantity",
        "value": "110 switches"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/switch-set-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/switch-set-2.webp",
      "thumb": "https://media.nexusohm.com/products/switch-set-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/switch-set-1.webp",
        "https://media.nexusohm.com/products/switch-set-2.webp",
        "https://media.nexusohm.com/products/switch-set-3.webp",
        "https://media.nexusohm.com/products/switch-set-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Nebula Violet",
        "hex": "#5B3BFF"
      }
    ]
  },
  {
    "id": "k-pro-mouse",
    "sku": "KEY-M6-132",
    "brand": "KEYCHRON",
    "title": "M6 Wireless Mouse",
    "category": "peripherals",
    "priceMinor": 8900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 28,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "26K DPI PixArt PAW3395",
      "Ergonomic right-hand shape",
      "Up to 120h battery"
    ],
    "specs": [
      {
        "label": "Sensor",
        "value": "PixArt PAW3395, up to 26,000 DPI"
      },
      {
        "label": "Polling",
        "value": "1000Hz (4000Hz version available)"
      },
      {
        "label": "Shape",
        "value": "Ergonomic, right-handed, with thumb scroll wheel"
      },
      {
        "label": "Switches",
        "value": "Huano, 80 million clicks"
      },
      {
        "label": "Connectivity",
        "value": "2.4GHz, Bluetooth 5.1, USB-C wired"
      },
      {
        "label": "Battery",
        "value": "800mAh, up to 120 hours at 1000Hz"
      },
      {
        "label": "Software",
        "value": "Keychron Launcher (web)"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/k-pro-mouse-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/k-pro-mouse-2.webp",
      "thumb": "https://media.nexusohm.com/products/k-pro-mouse-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/k-pro-mouse-1.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-2.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-3.webp",
        "https://media.nexusohm.com/products/k-pro-mouse-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  },
  {
    "id": "op1-field",
    "sku": "TE-OP1F-133",
    "brand": "TEENAGE_ENGINEERING",
    "title": "OP-1 Field Synthesizer",
    "category": "audio",
    "priceMinor": 199900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 12,
    "badge": "LIMITED_EDITION",
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "32-bit audio engine",
      "24-hour battery",
      "Bluetooth MIDI, FM radio"
    ],
    "specs": [
      {
        "label": "Engine",
        "value": "32-bit audio throughout"
      },
      {
        "label": "Battery",
        "value": "24 hours"
      },
      {
        "label": "Synthesis",
        "value": "8 stereo engines: Cluster, Digital, FM, Phase, Pulse, String, Voltage, Dimension"
      },
      {
        "label": "Tape",
        "value": "Up to 8 swappable stereo tapes"
      },
      {
        "label": "Sampling",
        "value": "Up to 20 seconds per sample"
      },
      {
        "label": "Connectivity",
        "value": "Bluetooth MIDI, USB-C audio interface, FM radio (receive and transmit)"
      },
      {
        "label": "Display",
        "value": "High-resolution, under hardened glass"
      },
      {
        "label": "Size and weight",
        "value": "300 × 120 × 20 mm, 590 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/op1-field-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/op1-field-2.webp",
      "thumb": "https://media.nexusohm.com/products/op1-field-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/op1-field-1.webp",
        "https://media.nexusohm.com/products/op1-field-2.webp",
        "https://media.nexusohm.com/products/op1-field-3.webp",
        "https://media.nexusohm.com/products/op1-field-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      },
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      }
    ]
  },
  {
    "id": "tp7-recorder",
    "sku": "TE-TP7-134",
    "brand": "TEENAGE_ENGINEERING",
    "title": "TP-7 Field Recorder",
    "category": "audio",
    "priceMinor": 149900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 7,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "128GB internal storage",
      "Motorised tape reel",
      "7-hour battery"
    ],
    "specs": [
      {
        "label": "Storage",
        "value": "128GB internal"
      },
      {
        "label": "Battery",
        "value": "7 hours, rechargeable"
      },
      {
        "label": "Reel",
        "value": "Motorised tape reel with a brushless motor"
      },
      {
        "label": "Jacks",
        "value": "3 × 3.5mm stereo in/out (TRRS), 3.5mm headphone out"
      },
      {
        "label": "USB-C",
        "value": "Multichannel audio interface, MIDI, data and charging"
      },
      {
        "label": "Microphone",
        "value": "Built in"
      },
      {
        "label": "Transcription",
        "value": "In the TP–7 app"
      },
      {
        "label": "Size and weight",
        "value": "96 × 68 × 16 mm, 170 g"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/tp7-recorder-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/tp7-recorder-2.webp",
      "thumb": "https://media.nexusohm.com/products/tp7-recorder-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/tp7-recorder-1.webp",
        "https://media.nexusohm.com/products/tp7-recorder-2.webp",
        "https://media.nexusohm.com/products/tp7-recorder-3.webp",
        "https://media.nexusohm.com/products/tp7-recorder-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Silver",
        "hex": "#D4D4D8"
      }
    ]
  },
  {
    "id": "ob4-speaker",
    "sku": "TE-OB4-135",
    "brand": "TEENAGE_ENGINEERING",
    "title": "OB-4 Magic Radio",
    "category": "audio",
    "priceMinor": 64900,
    "currency": "USD",
    "inStock": true,
    "stockCount": 11,
    "rating": 0,
    "reviewCount": 0,
    "specsSummary": [
      "Two 38-watt class-D amps",
      "2-hour rolling recording",
      "Up to 72h on FM radio"
    ],
    "specs": [
      {
        "label": "Drivers",
        "value": "Long-throw neodymium woofers, ferrofluid-cooled neodymium tweeters"
      },
      {
        "label": "Amplifier",
        "value": "2 × 38 watts, class D"
      },
      {
        "label": "Recording",
        "value": "Always-on 2-hour rolling buffer"
      },
      {
        "label": "Sources",
        "value": "FM radio, Bluetooth (AAC), 3.5mm line in, disk modes"
      },
      {
        "label": "Battery",
        "value": "Up to 72 hours (FM, normal volume), 8 hours (Bluetooth, high volume)"
      },
      {
        "label": "Controls",
        "value": "Motorised tape reel and volume knob"
      },
      {
        "label": "Build",
        "value": "Glass-fibre reinforced PC and milled aluminium"
      },
      {
        "label": "Size and weight",
        "value": "232.5 × 284 × 57.5 mm, 1.7 kg"
      }
    ],
    "media": {
      "heroImage": "https://media.nexusohm.com/products/ob4-speaker-1.webp",
      "hoverImage": "https://media.nexusohm.com/products/ob4-speaker-2.webp",
      "thumb": "https://media.nexusohm.com/products/ob4-speaker-thumb.webp",
      "gallery": [
        "https://media.nexusohm.com/products/ob4-speaker-1.webp",
        "https://media.nexusohm.com/products/ob4-speaker-2.webp",
        "https://media.nexusohm.com/products/ob4-speaker-3.webp",
        "https://media.nexusohm.com/products/ob4-speaker-4.webp"
      ]
    },
    "colorways": [
      {
        "name": "Midnight",
        "hex": "#1C1C1F"
      },
      {
        "name": "Starlight",
        "hex": "#EDEDEF"
      }
    ]
  }
]

/** The hero's featured drop. */
export const featuredDrop: Product = products.find((p) => p.sku === 'DJI-MV4-115')!
